// Contenu de « Je n'ai jamais » : questions (par mode), questions rares, punitions
// et bonus (par niveau d'alcool). Repris de l'ancienne version.

export const QUESTIONS = {
  Chill: [
    "Je n’ai jamais fini une série en une nuit.",
    "Je n’ai jamais pleuré devant un film d’animation.",
    "Je n’ai jamais stalké quelqu’un pendant des heures sur les réseaux.",
    "Je n’ai jamais menti sur mon âge.",
    "Je n’ai jamais oublié l’anniversaire de ma mère.",
    "Je n’ai jamais eu un crush sur un personnage fictif.",
    "Je n’ai jamais mangé une pizza froide le lendemain.",
    "Je n’ai jamais fait semblant d’aimer un cadeau.",
    "Je n’ai jamais gardé un objet trouvé sans chercher le proprio.",
    "Je n’ai jamais fait une liste de résolutions du Nouvel An.",
    "Je n’ai jamais dormi avec la lumière allumée après 15 ans.",
    "Je n’ai jamais collectionné des figurines.",
    "Je n’ai jamais fait du sport juste pour poster des photos.",
    "Je n’ai jamais cuisiné un vrai repas pour moi seul.",
    "Je n’ai jamais appris une langue pour impressionner quelqu’un.",
    "Je n’ai jamais pleuré en écoutant une chanson.",
    "Je n’ai jamais eu peur du noir après 18 ans.",
    "Je n’ai jamais envoyé un message d’amour sans l’envoyer.",
    "Je n’ai jamais fait semblant de connaître un artiste.",
    "Je n’ai jamais gardé tous mes ex en ami.",
    "Je n’ai jamais fait une tier list de mes ex.",
    "Je n’ai jamais parlé tout seul dans la rue.",
    "Je n’ai jamais collectionné des mugs mignons.",
    "Je n’ai jamais fait du journaling pendant plus d’une semaine.",
    "Je n’ai jamais eu peur des araignées.",
    "Je n’ai jamais dit ‘je vais me coucher tôt’ et fait tout l’inverse.",
    "Je n’ai jamais eu une playlist sad girl/boy hours.",
    "Je n’ai jamais fait des recherches Wikipédia à 4h du matin.",
    "Je n’ai jamais parlé à mes plantes.",
    "Je n’ai jamais eu 50 onglets ouverts en même temps.",
    "Je n’ai jamais fait des siestes de 4 heures.",
    "Je n’ai jamais ri tout seul avec un meme.",
    "Je n’ai jamais gardé tous mes tickets de caisse.",
    "Je n’ai jamais eu peur des clowns.",
    "Je n’ai jamais dit ‘je t’aime’ bourré à mes potes.",
    "Je n’ai jamais collectionné les Polaroid.",
    "Je n’ai jamais tenu mes résolutions plus de 3 jours.",
    "Je n’ai jamais fait des voix bizarres au téléphone.",
    "Je n’ai jamais collectionné les stickers.",
    "Je n’ai jamais eu une peur irrationnelle des pigeons.",
    "Je n’ai jamais parlé en dormant.",
    "Je n’ai jamais été le plus gentil du groupe.",
    "Je n’ai jamais fait des selfies avec des inconnus.",
    "Je n’ai jamais gardé une lettre d’amour.",
    "Je n’ai jamais cherché mes symptômes sur Google en paniquant.",
    "Je n’ai jamais dit « juste un épisode »… et regardé toute la saison.",
    "Je n’ai jamais fait des voix en message vocal.",
    "Je n’ai jamais été addict aux stories Instagram.",
    "Je n’ai jamais fait des listes sans jamais rien faire.",
    "Je n’ai jamais eu un carnet de pensées profondes.",
    "Je n’ai jamais dansé seul dans ma chambre.",
    "Je n’ai jamais été le thérapeute du groupe.",
    "Je n’ai jamais dit ‘je change’ tous les mois.",
    "Je n’ai jamais eu une playlist pour chaque mood.",
    "Je n’ai jamais fait des câlins très longs.",
    "Je n’ai jamais parlé de mes rêves lucides.",
    "Je n’ai jamais grignoté healthy puis junk food juste après.",
    "Je n’ai jamais fait des tier lists de mes potes.",
    "Je n’ai jamais gardé tous mes bracelets brésiliens.",
    "Je n’ai jamais fait des blagues nulles pour détendre l’atmosphère.",
    "Je n’ai jamais eu peur des hauteurs.",
    "Je n’ai jamais collectionné les hoodies oversize.",
    "Je n’ai jamais fait des grimaces sur toutes les photos.",
    "Je n’ai jamais posé des questions existentielles à 3h du matin.",
    "Je n’ai jamais eu une routine skincare de 12 étapes.",
    "Je n’ai jamais dit ‘je suis fatigué’ toute la soirée.",
    "Je n’ai jamais été obsédé par le rangement.",
    "Je n’ai jamais fait des DIY complètement ratés.",
    "Je n’ai jamais chanté en voiture comme une star.",
    "Je n’ai jamais eu une addiction au café.",
    "Je n’ai jamais fait des mimes en racontant une histoire.",
    "Je n’ai jamais eu une chambre qui ressemble à un champ de bataille.",
    "Je n’ai jamais posé des questions philo bourré.",
    "Je n’ai jamais fait des sons bizarres en mangeant.",
    "Je n’ai jamais gardé tous mes souvenirs d’enfance.",
    "Je n’ai jamais dit oui à tout puis regretté.",
    "Je n’ai jamais fait des danses TikTok ratées.",
    "Je n’ai jamais eu des chaussettes dépareillées.",
    "Je n’ai jamais blagué sur mon propre malheur.",
    "Je n’ai jamais eu 10 projets commencés et aucun fini.",
    "Je n’ai jamais fait des compliments random sincères.",
    "Je n’ai jamais été toujours en retard avec une bonne excuse.",
    "Je n’ai jamais fait des jeux de mots pourris.",
    "Je n’ai jamais parlé en citations de séries.",
    "Je n’ai jamais cru aux signes de l’univers.",
    "Je n’ai jamais raconté mes rêves bizarres à tout le monde.",
    "Je n’ai jamais chanté sous la douche.",
    "Je n’ai jamais fait des listes pour tout.",
    "Je n’ai jamais fini mes phrases par des emojis.",
    "Je n’ai jamais regardé des mukbangs pour m’endormir.",
    "Je n’ai jamais dit ‘c’est pas ce que je voulais dire’.",
    "Je n’ai jamais aimé les dramas des autres.",
    "Je n’ai jamais eu une peluche secrète.",
    "Je n’ai jamais chanté sous la pluie.",
    "Je n’ai jamais oublié de manger de la journée.",
    "Je n’ai jamais fait des câlins à tout le monde.",
    "Je n’ai jamais fait des voix aux animaux.",
    "Je n’ai jamais été toujours en train de grignoter.",
    "Je n’ai jamais pris des notes sur tout.",
    "Je n’ai jamais aimé les films d’horreur mais eu peur après.",
    "Je n’ai jamais fait semblant d’être au téléphone pour éviter quelqu’un.",
    "Je n’ai jamais relu une conversation entière avec un ex.",
    "Je n’ai jamais envoyé un message vocal par erreur.",
    "Je n’ai jamais fait un câlin à un arbre.",
    "Je n’ai jamais pleuré en regardant une pub.",
    "Je n’ai jamais raté une marche devant plein de monde.",
    "Je n’ai jamais salué quelqu’un qui ne me saluait pas.",
    "Je n’ai jamais ri au mauvais moment pendant un moment sérieux.",
    "Je n’ai jamais menti sur un film pour avoir l’air cultivé.",
    "Je n’ai jamais dormi pendant un film au cinéma.",
  ],
  Party: [
    "Je n’ai jamais vomi dans un Uber.",
    "Je n’ai jamais fait un striptease raté.",
    "Je n’ai jamais perdu mon téléphone en soirée.",
    "Je n’ai jamais embrassé quelqu’un dont je ne connaissais pas le prénom.",
    "Je n’ai jamais gardé un verre de bar en souvenir.",
    "Je n’ai jamais fait un body shot.",
    "Je n’ai jamais dansé sur le bar.",
    "Je n’ai jamais fini à poil dans une piscine.",
    "Je n’ai jamais ramené quelqu’un sans me souvenir de son visage.",
    "Je n’ai jamais fait un shot dans le nombril.",
    "Je n’ai jamais perdu une chaussure en rentrant.",
    "Je n’ai jamais crié des confessions dans la rue.",
    "Je n’ai jamais fait un pari coquin.",
    "Je n’ai jamais fini chez un inconnu.",
    "Je n’ai jamais fait un karaoké bourré.",
    "Je n’ai jamais ramené un objet improbable d’une soirée.",
    "Je n’ai jamais dormi dans une baignoire.",
    "Je n’ai jamais fait un french kiss à plusieurs personnes la même nuit.",
    "Je n’ai jamais goûté un cocktail inventé par un pote… et regretté.",
    "Je n’ai jamais vomi puis continué à boire.",
    "Je n’ai jamais fait un twerk sur un pote.",
    "Je n’ai jamais perdu mon portefeuille en soirée.",
    "Je n’ai jamais dansé en slip.",
    "Je n’ai jamais ramené tout le monde chez moi.",
    "Je n’ai jamais fait un after jusqu’à 14h.",
    "Je n’ai jamais fait un limbo avec une bouteille.",
    "Je n’ai jamais chanté en duo bourré.",
    "Je n’ai jamais fait un battle de danse.",
    "Je n’ai jamais fini avec des bisous partout.",
    "Je n’ai jamais fait un toast à n’importe quoi.",
    "Je n’ai jamais fait un flip cup.",
    "Je n’ai jamais dansé sur la table basse.",
    "Je n’ai jamais fait un beer pong raté.",
    "Je n’ai jamais perdu mes affaires partout.",
    "Je n’ai jamais fait un mur de shot.",
    "Je n’ai jamais dansé avec un inconnu toute la soirée.",
    "Je n’ai jamais fait un never have I ever sauvage.",
    "Je n’ai jamais fini la bouteille de vodka.",
    "Je n’ai jamais chanté du hardstyle bourré.",
    "Je n’ai jamais ramené quelqu’un dans les toilettes.",
    "Je n’ai jamais fait un strip poker.",
    "Je n’ai jamais crié ‘shots shots shots’.",
    "Je n’ai jamais dansé sur du reggaeton.",
    "Je n’ai jamais fini avec du maquillage sur le visage.",
    "Je n’ai jamais fait un challenge TikTok bourré.",
    "Je n’ai jamais perdu mon Uber.",
    "Je n’ai jamais mixé Red Bull avec n’importe quoi.",
    "Je n’ai jamais chanté en play-back sur du rap.",
    "Je n’ai jamais dansé sous la pluie.",
    "Je n’ai jamais crié mon ex sur la piste.",
    "Je n’ai jamais fait un shot gun.",
    "Je n’ai jamais dansé en chaussettes.",
    "Je n’ai jamais ramené tout le groupe à l’after.",
    "Je n’ai jamais fait un karaoké seul sur scène.",
    "Je n’ai jamais fini torse nu sur une story.",
    "Je n’ai jamais perdu mes lunettes en dansant.",
    "Je n’ai jamais dansé sur une musique triste.",
    "Je n’ai jamais ramené un invité surprise à une soirée.",
    "Je n’ai jamais fait un striptease sur une table.",
    "Je n’ai jamais crié ‘je suis la star’.",
    "Je n’ai jamais dansé avec une lampe.",
    "Je n’ai jamais fait un battle de twerk.",
    "Je n’ai jamais fini avec des traces de rouge à lèvres partout.",
    "Je n’ai jamais dansé collé-serré avec tout le monde.",
    "Je n’ai jamais fait un conga line.",
    "Je n’ai jamais invité des randoms.",
    "Je n’ai jamais pris des photos de tout le monde bourré.",
    "Je n’ai jamais dansé sur du son de merde.",
    "Je n’ai jamais fait un moonwalk raté.",
    "Je n’ai jamais ramené 5 inconnus.",
    "Je n’ai jamais fait un body shot sur un pote.",
    "Je n’ai jamais fait un french kiss à un pote.",
    "Je n’ai jamais mixé tous les alcools.",
    "Je n’ai jamais fait un karaoké dramatique.",
    "Je n’ai jamais fini en string.",
    "Je n’ai jamais dansé jusqu’à la fermeture.",
    "Je n’ai jamais fait un discours d’ivrogne à toute la soirée.",
    "Je n’ai jamais chanté faux tout un karaoké sans m’en rendre compte.",
    "Je n’ai jamais perdu le fil de la conversation en plein milieu de ma phrase.",
    "Je n’ai jamais appelé un taxi pour un trajet de 5 minutes.",
    "Je n’ai jamais pris 200 photos sans en garder une seule.",
    "Je n’ai jamais trinqué avec un inconnu au bar.",
    "Je n’ai jamais fait le DJ sans qu’on me le demande.",
    "Je n’ai jamais commandé un cocktail juste pour son nom.",
    "Je n’ai jamais dansé avec un balai ou une lampe.",
    "Je n’ai jamais fait le tour de la soirée pour présenter mon nouveau meilleur ami.",
    "Je n’ai jamais fini la soirée en chaussettes.",
    "Je n’ai jamais découvert un tampon de boîte de nuit sur ma main sans savoir d’où il venait.",
    "Je n’ai jamais dragué quelqu’un avec une phrase de film.",
    "Je n’ai jamais fait la queue une heure pour une boîte… et été refoulé.",
    "Je n’ai jamais bu dans une chaussure.",
    "Je n’ai jamais perdu mon manteau dans une soirée.",
    "Je n’ai jamais fait un concours de danse et perdu contre un inconnu.",
    "Je n’ai jamais dormi sur le canapé d’une soirée sans demander.",
    "Je n’ai jamais envoyé un message groupé que je regrette.",
    "Je n’ai jamais raconté la même blague trois fois dans la soirée.",
    "Je n’ai jamais réussi à rentrer dans une soirée sans être invité.",
    "Je n’ai jamais perdu ma voix en chantant en boîte.",
    "Je n’ai jamais fait une soirée pyjama à plus de 20 ans.",
    "Je n’ai jamais fini une soirée en mangeant des pâtes à 4h du matin.",
    "Je n’ai jamais oublié où j’avais garé ma voiture après une soirée.",
  ],
  Chaos: [
    "Je n’ai jamais réveillé tout l’immeuble en rentrant.",
    "Je n’ai jamais fait un tatouage sur un coup de tête.",
    "Je n’ai jamais perdu mes chaussures en soirée.",
    "Je n’ai jamais cassé mon téléphone en étant bourré.",
    "Je n’ai jamais sauté tout habillé dans une piscine.",
    "Je n’ai jamais vomi sur quelqu’un.",
    "Je n’ai jamais couru tout nu dehors.",
    "Je n’ai jamais déclenché une alarme par accident.",
    "Je n’ai jamais lancé une guerre de nourriture.",
    "Je n’ai jamais fait un combat de polochons à 4h du matin.",
    "Je n’ai jamais fait un canular téléphonique.",
    "Je n’ai jamais fait un roulé-boulé en pleine soirée.",
    "Je n’ai jamais fait un strip-tease sur un balcon.",
    "Je n’ai jamais hurlé mon amour à quelqu’un à 5h du matin.",
    "Je n’ai jamais fait un pari de bouffe dégueulasse.",
    "Je n’ai jamais vomi dans un endroit très inattendu.",
    "Je n’ai jamais posté une story que j’ai supprimée le lendemain.",
    "Je n’ai jamais fait un live complètement à l’ouest.",
    "Je n’ai jamais cassé un truc chez quelqu’un en faisant comme si de rien n’était.",
    "Je n’ai jamais dormi dans le jardin de quelqu’un.",
    "Je n’ai jamais fini une soirée dans une ville où je n’étais pas censé être.",
    "Je n’ai jamais pris le bus ou le train dans la mauvaise direction en rentrant de soirée.",
    "Je n’ai jamais raté le dernier métro et marché des heures.",
    "Je n’ai jamais fait la fête trois jours de suite.",
    "Je n’ai jamais enchaîné une soirée et une journée de boulot ou de cours sans dormir.",
    "Je n’ai jamais menti à mes parents sur l’endroit où je dormais.",
    "Je n’ai jamais fait le mur.",
    "Je n’ai jamais été viré d’une soirée.",
    "Je n’ai jamais été refoulé à l’entrée d’une boîte.",
    "Je n’ai jamais dansé sur une table.",
    "Je n’ai jamais grimpé sur le comptoir d’un bar.",
    "Je n’ai jamais pris le micro dans un bar sans y être invité.",
    "Je n’ai jamais monopolisé le micro d’un karaoké toute la soirée.",
    "Je n’ai jamais lancé un pogo tout seul.",
    "Je n’ai jamais perdu la voix à force de crier en soirée.",
    "Je n’ai jamais été dessiné dessus en m’endormant en soirée.",
    "Je n’ai jamais dessiné sur quelqu’un qui dormait.",
    "Je n’ai jamais mangé un truc tombé par terre en soirée.",
    "Je n’ai jamais commandé à manger à 5h du matin.",
    "Je n’ai jamais fini une soirée aux urgences pour une bêtise.",
    "Je n’ai jamais été le seul déguisé à une soirée.",
    "Je n’ai jamais organisé une soirée chez mes parents sans leur dire.",
    "Je n’ai jamais caché des dégâts avant le retour de mes parents.",
    "Je n’ai jamais fait débarquer les voisins à cause du bruit.",
    "Je n’ai jamais eu la visite de la police pour tapage.",
    "Je n’ai jamais dormi dans une voiture après une soirée.",
    "Je n’ai jamais perdu mes clés et dormi chez quelqu’un par obligation.",
    "Je n’ai jamais envoyé un vocal de 5 minutes que je n’ai jamais osé réécouter.",
    "Je n’ai jamais appelé mon ex en pleine nuit.",
    "Je n’ai jamais répondu à un « tu dors ? ».",
    "Je n’ai jamais fait un saut en parachute ou à l’élastique.",
    "Je n’ai jamais fait un road trip sans rien prévoir.",
    "Je n’ai jamais pris un avion sur un coup de tête.",
    "Je n’ai jamais fait une nuit blanche juste pour voir le lever du soleil.",
    "Je n’ai jamais dormi à la belle étoile.",
    "Je n’ai jamais fait un bain de minuit.",
    "Je n’ai jamais fait du camping sauvage.",
    "Je n’ai jamais escaladé une clôture pour entrer quelque part.",
    "Je n’ai jamais été coincé dans un ascenseur.",
    "Je n’ai jamais été enfermé dehors en pyjama.",
    "Je n’ai jamais fait un feu de camp qui a mal tourné.",
    "Je n’ai jamais cassé une chaise en m’asseyant dessus.",
    "Je n’ai jamais fait tomber un gâteau d’anniversaire.",
    "Je n’ai jamais raté un discours à un mariage.",
    "Je n’ai jamais dit « je ne bois plus jamais »… et rebu le soir même.",
    "Je n’ai jamais mélangé tous les alcools de la soirée dans un seul verre.",
    "Je n’ai jamais fait un concours de celui qui mange le plus.",
    "Je n’ai jamais mangé un piment beaucoup trop fort pour un pari.",
    "Je n’ai jamais perdu un pari et dû le payer très cher.",
    "Je n’ai jamais teint mes cheveux d’une couleur flashy sur un coup de tête.",
    "Je n’ai jamais rasé une partie de ma tête pour un pari.",
    "Je n’ai jamais débarqué à une soirée où je ne connaissais personne.",
    "Je n’ai jamais fini la soirée avec des gens dont je ne connaissais pas le prénom.",
    "Je n’ai jamais été le dernier à partir d’une soirée.",
    "Je n’ai jamais fait la fermeture d’une boîte de nuit.",
    "Je n’ai jamais enchaîné trois boîtes dans la même nuit.",
    "Je n’ai jamais fait un after qui a duré jusqu’à midi.",
    "Je n’ai jamais fait un selfie avec une célébrité en soirée.",
    "Je n’ai jamais fait un battle de danse avec un inconnu.",
    "Je n’ai jamais lancé une ola dans un bar.",
    "Je n’ai jamais perdu mes potes en festival.",
    "Je n’ai jamais dormi dans une tente détrempée en festival.",
    "Je n’ai jamais fait un festival sans me laver pendant 3 jours.",
    "Je n’ai jamais été porté par la foule dans un concert.",
    "Je n’ai jamais fini sur scène pendant un concert.",
    "Je n’ai jamais parlé à un inconnu toute la nuit sans jamais le revoir.",
    "Je n’ai jamais rentré à cloche-pied après avoir perdu une chaussure.",
    "Je n’ai jamais fait du karaoké jusqu’à l’aube.",
    "Je n’ai jamais été réveillé par les pompiers ou les voisins.",
    "Je n’ai jamais fait un pari qui a fini aux urgences.",
    "Je n’ai jamais crié un secret devant tout le monde.",
    "Je n’ai jamais dormi dans une soirée où je n’étais pas invité à rester.",
    "Je n’ai jamais fini une soirée en caleçon ou en culotte.",
    "Je n’ai jamais dansé avec un videur.",
    "Je n’ai jamais fait un tour de manège juste après avoir trop bu.",
    "Je n’ai jamais pris une douche tout habillé en rentrant de soirée.",
    "Je n’ai jamais réveillé quelqu’un en hurlant pour une blague.",
    "Je n’ai jamais mangé une pizza entière tout seul à 4h du matin.",
  ],
  Hardcore: [
    "Je n’ai jamais eu un crush sur quelqu’un du même sexe.",
    "Je n’ai jamais fantasmé sur un pote.",
    "Je n’ai jamais eu peur que mes parents découvrent mes DMs.",
    "Je n’ai jamais eu un crush sur un prof.",
    "Je n’ai jamais eu un crush sur le partenaire de mon pote.",
    "Je n’ai jamais eu un crush sur le frère ou la sœur d’un pote.",
    "Je n’ai jamais stalké mon ex pendant des heures.",
    "Je n’ai jamais stalké le crush de mon pote.",
    "Je n’ai jamais liké un post vieux de plusieurs années par accident.",
    "Je n’ai jamais eu peur que quelqu’un fouille mon téléphone.",
    "Je n’ai jamais envoyé un message à la mauvaise personne.",
    "Je n’ai jamais dit je t’aime bourré à la mauvaise personne.",
    "Je n’ai jamais regretté une soirée entière.",
    "Je n’ai jamais eu un fantasme que je ne pourrai jamais assumer.",
    "Je n’ai jamais envoyé un message que je regrette encore aujourd’hui.",
    "Je n’ai jamais eu une phase que je nierai jusqu’à ma mort.",
    "Je n’ai jamais eu une conversation impossible à défendre publiquement.",
    "Je n’ai jamais fait semblant d’être sobre devant mes parents.",
    "Je n’ai jamais pleuré bourré devant tout le monde.",
    "Je n’ai jamais dit des secrets que je n’aurais jamais dû dire.",
    "Je n’ai jamais ghosté quelqu’un.",
    "Je n’ai jamais été ghosté après avoir beaucoup parlé.",
    "Je n’ai jamais menti sur mon âge sur les réseaux ou les apps.",
    "Je n’ai jamais eu un compte fake ou finsta.",
    "Je n’ai jamais parlé mal de quelqu’un puis fait genre rien.",
    "Je n’ai jamais trahi un secret d’un pote.",
    "Je n’ai jamais fait semblant d’aimer quelque chose pour plaire.",
    "Je n’ai jamais eu un crush sur quelqu’un ici présent.",
    "Je n’ai jamais dragué quelqu’un alors que j’étais en couple.",
    "Je n’ai jamais eu une situationship toxique.",
    "Je n’ai jamais été bloqué par quelqu’un.",
    "Je n’ai jamais bloqué quelqu’un par jalousie.",
    "Je n’ai jamais menti sur mon nombre de relations.",
    "Je n’ai jamais fait semblant d’avoir de l’expérience.",
    "Je n’ai jamais dit des trucs chelous en étant bourré.",
    "Je n’ai jamais fini bourré en premier dans une soirée.",
    "Je n’ai jamais vomi en soirée.",
    "Je n’ai jamais perdu mon téléphone ou mes affaires bourré.",
    "Je n’ai jamais ramené quelqu’un dont je ne me souviens plus.",
    "Je n’ai jamais embrassé quelqu’un par défi.",
    "Je n’ai jamais dansé collé-serré avec un inconnu.",
    "Je n’ai jamais fait un pari stupide bourré.",
    "Je n’ai jamais fini à poil par accident ou par défi.",
    "Je n’ai jamais dragué quelqu’un de beaucoup plus vieux.",
    "Je n’ai jamais eu un date catastrophique.",
    "Je n’ai jamais été pris en flag en train de mater quelqu’un.",
    "Je n’ai jamais eu un rendez-vous qui s’est fini hyper mal.",
    "Je n’ai jamais dit je t’aime trop tôt.",
    "Je n’ai jamais eu une relation à distance cheloue.",
    "Je n’ai jamais fait du sexting pendant un cours.",
    "Je n’ai jamais eu peur que mes parents voient mes messages.",
    "Je n’ai jamais liké un post de mon ex par accident.",
    "Je n’ai jamais eu un crush sur un influenceur.",
    "Je n’ai jamais fait semblant d’être vierge.",
    "Je n’ai jamais eu un crush sur le meilleur ami de mon ex.",
    "Je n’ai jamais dit un secret en étant bourré.",
    "Je n’ai jamais eu un kink que j’oserais jamais avouer.",
    "Je n’ai jamais regretté d’avoir ajouté quelqu’un sur Snap.",
    "Je n’ai jamais eu une conversation super gênante par message.",
    "Je n’ai jamais regretté mon premier baiser.",
    "Je n’ai jamais eu des sentiments pour un pote qui ne pouvait pas me les rendre.",
    "Je n’ai jamais fait semblant d’être intéressé juste pour l’attention.",
    "Je n’ai jamais eu peur d’attraper une IST.",
    "Je n’ai jamais comparé mon corps à celui d’un pote.",
    "Je n’ai jamais eu un crush sur quelqu’un de ma promo.",
    "Je n’ai jamais été obsédé par quelqu’un.",
    "Je n’ai jamais eu peur que toute ma vie sorte au grand jour.",
    "Je n’ai jamais eu une phase où je mentais sur tout.",
    "Je n’ai jamais fait semblant d’aimer un style de musique.",
    "Je n’ai jamais copié quelqu’un pour être accepté.",
    "Je n’ai jamais eu un compte privé pour espionner.",
    "Je n’ai jamais jugé quelqu’un puis fait pareil.",
    "Je n’ai jamais eu peur d’être jugé pour mes goûts.",
    "Je n’ai jamais eu un énorme regret de message vocal.",
    "Je n’ai jamais fini la soirée à pleurer dans un coin.",
    "Je n’ai jamais inventé une vie parfaite sur les réseaux.",
    "Je n’ai jamais eu un crush sur un streamer.",
    "Je n’ai jamais fait semblant de connaître une personne célèbre.",
    "Je n’ai jamais eu honte de mes parents devant mes potes.",
    "Je n’ai jamais fait semblant d’avoir vu un film ou une série.",
    "Je n’ai jamais menti sur mes notes.",
    "Je n’ai jamais triché à un examen.",
    "Je n’ai jamais eu peur d’être le moins expérimenté du groupe.",
    "Je n’ai jamais fait un pari que j’ai regretté.",
    "Je n’ai jamais eu peur que mes potes se moquent de moi.",
    "Je n’ai jamais dit du mal de tout le groupe puis fait genre rien.",
    "Je n’ai jamais eu un énorme crush non réciproque.",
    "Je n’ai jamais été rejeté de façon humiliante.",
    "Je n’ai jamais eu peur d’être le plus immature du groupe.",
    "Je n’ai jamais fait semblant d’être cool avec quelque chose qui me touche.",
    "Je n’ai jamais eu un moment ultra cringe sur les réseaux.",
    "Je n’ai jamais regretté mon style vestimentaire d’avant.",
    "Je n’ai jamais fait semblant d’avoir déjà couché.",
    "Je n’ai jamais eu un crush sur quelqu’un d’inaccessible.",
    "Je n’ai jamais été super jaloux d’un pote.",
    "Je n’ai jamais eu peur que tout le monde me juge.",
    "Je n’ai jamais dit oui à un truc pour ne pas passer pour un trouillard.",
    "Je n’ai jamais embrassé deux personnes dans la même soirée.",
    "Je n’ai jamais couché le premier soir.",
    "Je n’ai jamais envoyé un nude.",
    "Je n’ai jamais envoyé un nude à la mauvaise personne.",
    "Je n’ai jamais fait l’amour dans un endroit insolite.",
    "Je n’ai jamais simulé.",
    "Je n’ai jamais fait un plan à trois.",
    "Je n’ai jamais eu un plan cul.",
    "Je n’ai jamais eu un coup d’un soir dont j’ai oublié le prénom.",
    "Je n’ai jamais fait un walk of shame.",
    "Je n’ai jamais eu deux dates le même jour.",
    "Je n’ai jamais été surpris en pleine action.",
    "Je n’ai jamais fait un strip-tease pour quelqu’un.",
    "Je n’ai jamais eu un fantasme sur quelqu’un de cette pièce.",
    "Je n’ai jamais embrassé quelqu’un de cette pièce.",
    "Je n’ai jamais eu une histoire avec un collègue.",
    "Je n’ai jamais eu une relation cachée.",
    "Je n’ai jamais trompé quelqu’un.",
    "Je n’ai jamais été trompé.",
    "Je n’ai jamais été l’amant ou la maîtresse de quelqu’un.",
    "Je n’ai jamais fait du sexting.",
    "Je n’ai jamais fait un appel vidéo très privé.",
    "Je n’ai jamais eu un jouet sexuel.",
    "Je n’ai jamais réveillé mes voisins… et pas en ronflant.",
    "Je n’ai jamais eu un plan dans une voiture.",
    "Je n’ai jamais été tenté de répondre à un ex en pleine nuit… et répondu.",
    "Je n’ai jamais dragué quelqu’un pour rendre mon ex jaloux.",
    "Je n’ai jamais eu un crush sur la ou le partenaire d’un pote.",
    "Je n’ai jamais fini la soirée chez quelqu’un rencontré le soir même.",
    "Je n’ai jamais dit le prénom d’un ex au mauvais moment.",
  ],
};

export const RARE_QUESTIONS = {
  Chill: [
    "QUESTION RARE 😇 : Je n’ai jamais eu un crush secret ridicule.",
    "QUESTION RARE 😇 : Je n’ai jamais fait semblant de ne pas voir quelqu’un.",
    "QUESTION RARE 😇 : Je n’ai jamais menti pour éviter un appel."
  ],
  Party: [
    "QUESTION RARE 🍻 : Je n’ai jamais embrassé quelqu’un en soirée.",
    "QUESTION RARE 🍻 : Je n’ai jamais regretté un message envoyé bourré.",
    "QUESTION RARE 🍻 : Je n’ai jamais flirté juste parce que j’avais bu."
  ],
  Chaos: [
    "QUESTION INTERDITE 💀 : Je n’ai jamais menti à quelqu’un présent ici.",
    "QUESTION INTERDITE 💀 : Je n’ai jamais eu un secret sur quelqu’un du groupe.",
    "QUESTION INTERDITE 💀 : Je n’ai jamais envoyé un message que je cache encore."
  ],
  Hardcore: [
    "QUESTION LÉGENDAIRE ☠️ : Je n’ai jamais été la pire version de moi-même en soirée.",
    "QUESTION LÉGENDAIRE ☠️ : Je n’ai jamais fait quelque chose que je nierai toujours.",
    "QUESTION LÉGENDAIRE ☠️ : Je n’ai jamais été sauvé par un pote après une énorme erreur."
  ]
};

export const BONUS = {
  did: {
    soft: [
      "💀 Le groupe veut les détails.",
      "🍺 Bois 1 gorgée bonus si c’est récent.",
      "😈 Choisis quelqu’un qui fait un mini-gage avec toi.",
      "👀 Raconte l’histoire ou bois 1 gorgée."
    ],
    normal: [
      "💀 Le groupe veut les détails.",
      "🍻 Bois 2 gorgées bonus si c’est récent.",
      "😈 Choisis quelqu’un qui boit avec toi.",
      "👀 Raconte l’histoire ou bois encore.",
      "🎯 Si quelqu’un ici était impliqué, vous buvez tous les deux."
    ],
    hard: [
      "🔥 Raconte l’histoire ou prends un shot.",
      "⚡ Si c’était cette année, double peine.",
      "☠️ Si tu refuses de raconter, shot ou vérité hardcore.",
      "🎯 Choisis quelqu’un qui boit avec toi 3 gorgées.",
      "💀 Le groupe peut poser une question obligatoire."
    ],
    danger: [
      "☠️ Raconte l’histoire ou DOUBLE SHOT.",
      "💀 Si quelqu’un ici était impliqué, vous prenez tous les deux un shot.",
      "🔥 Si tu refuses de répondre, cul sec ou sanction du groupe.",
      "🎲 Shot mystère si l’histoire date de moins d’un an.",
      "🩸 Le groupe choisit une question hardcore."
    ]
  },
  safe: [
    "😇 Trop sage pour cette question.",
    "🛡️ Safe, tu peux choisir quelqu’un qui boit.",
    "👑 Immunité morale pour ce tour.",
    "✨ Tu esquives le chaos.",
    "🎲 Tu peux forcer quelqu’un à répondre honnêtement.",
    "🍀 Coup de chance.",
    "🧊 Sang-froid validé.",
    "😂 Le groupe ne te croit pas forcément."
  ]
};
