// Actions (défis) par mode de soirée. Réalisables sur place, sans danger : le but est de rire.

export const DARES = {
  Chill: [
    "Fais ta meilleure imitation d'un animal pendant 10 secondes.",
    "Parle avec un accent de ton choix jusqu'à ton prochain tour.",
    "Fais un compliment sincère à chaque joueur.",
    "Chante le refrain de la dernière chanson que tu as écoutée.",
    "Fais 10 squats en comptant à voix haute.",
    "Raconte une blague. Si personne ne rit, recommence avec une autre.",
    "Imite un autre joueur jusqu'à ce que quelqu'un devine qui.",
    "Fais ta meilleure pose de mannequin pendant 15 secondes.",
    "Dis l'alphabet à l'envers le plus loin possible.",
    "Danse 20 secondes sans musique.",
    "Fais une déclaration d'amour dramatique à un objet de la pièce.",
    "Mime un film jusqu'à ce que le groupe trouve.",
    "Parle uniquement en chuchotant jusqu'à ton prochain tour.",
    "Fais le tour de la pièce en marchant comme un pingouin.",
    "Montre la dernière photo de ta galerie (tu peux en refuser une seule).",
    "Invente une chanson de 4 phrases sur le joueur à ta gauche.",
    "Fais un discours de 30 secondes pour ta candidature à la présidence.",
    "Tiens en équilibre sur un pied pendant 30 secondes.",
    "Dis 5 choses que tu aimes chez le joueur à ta droite.",
    "Fais ton meilleur cri de guerre.",
    "Présente la météo de demain comme à la télé.",
    "Imite ton prof ou ton chef le plus marquant.",
    "Fais un rap de 4 phrases sur la soirée.",
    "Donne ton téléphone à quelqu'un qui change ton fond d'écran pour la soirée.",
    "Parle à la troisième personne jusqu'à ton prochain tour.",
    "Fais 15 secondes de karaoké sur une chanson choisie par le groupe.",
    "Raconte ta journée comme un commentateur sportif.",
    "Fais deviner un métier en le mimant.",
    "Vends un objet de la pièce comme dans un téléachat.",
    "Fais une grimace et garde-la pendant une photo de groupe.",
    "Danse la macarena (ou essaie).",
    "Fais 10 pompes (ou 20 pompes sur les genoux).",
    "Écris un poème de 2 lignes sur le joueur de ton choix et lis-le.",
    "Joue un pierre-feuille-ciseaux contre tout le monde : si tu perds une fois, recommence le tour.",
    "Laisse le groupe choisir ton surnom pour le reste de la soirée.",
    "Fais ton meilleur moonwalk.",
    "Raconte une histoire en ne utilisant que des mots d'une syllabe.",
    "Appelle-toi « Votre Altesse » jusqu'à ton prochain tour (les autres aussi doivent).",
    "Fais une démonstration de yoga improvisée.",
    "Dis un virelangue 3 fois sans te tromper.",
    "Fais le bruit d'un animal choisi par le groupe à chaque fois que quelqu'un dit ton prénom (1 tour).",
    "Mime ta routine du matin.",
    "Fais une haie d'honneur avec ta voix pour chaque joueur qui se lève (1 tour).",
    "Imite une célébrité choisie par le groupe.",
    "Fais une battle de regard avec le joueur à ta gauche : le premier qui rit a perdu.",
    "Présente-toi comme si tu étais à un speed dating.",
    "Fais une chorégraphie de 10 secondes que tout le monde doit reproduire.",
    "Raconte la fin d'un film célèbre… complètement inventée.",
    "Dis « je suis une licorne » avec le plus grand sérieux.",
    "Fais une pub pour toi-même de 20 secondes."
  ],
  Party: [
    "Laisse le joueur à ta droite écrire un message (gentil) à la personne de ton choix depuis ton téléphone.",
    "Fais une danse sensuelle de 15 secondes… avec une chaise.",
    "Bois ton verre sans les mains (avec une paille ou pas).",
    "Échange un vêtement avec le joueur de ton choix jusqu'à ton prochain tour.",
    "Laisse le groupe regarder ta dernière recherche Google.",
    "Fais une déclaration enflammée au joueur de ton choix.",
    "Imite la façon de danser de chaque joueur.",
    "Laisse quelqu'un te dessiner une moustache (feutre, rouge à lèvres, ou à l'imaginaire).",
    "Fais un twerk de 10 secondes.",
    "Envoie « tu me manques » à la 5e personne de tes contacts (et assume la réponse).",
    "Fais une pub de parfum avec le joueur à ta gauche.",
    "Laisse le groupe lire ta dernière conversation (au choix entre 2).",
    "Fais une imitation de toi-même bourré.",
    "Montre ta playlist la plus gênante et mets-en une chanson.",
    "Fais une sérénade au joueur de ton choix.",
    "Tiens-toi la main avec le joueur à ta droite jusqu'à ton prochain tour.",
    "Raconte ton pire date en 30 secondes.",
    "Fais une démonstration de ton meilleur pas de danse en soirée.",
    "Laisse quelqu'un poster une story (validée par toi) sur ton compte.",
    "Fais 10 secondes de catwalk dans la pièce.",
    "Imite le cri de ton chanteur préféré.",
    "Fais un câlin de 10 secondes au joueur de ton choix.",
    "Bois une gorgée du verre de chaque joueur (qui accepte).",
    "Fais deviner une position du Kama-sutra… en mimant avec une chaise.",
    "Laisse le groupe te coiffer comme il veut pour le reste du tour.",
    "Appelle quelqu'un et chante-lui joyeux anniversaire (même si c'est pas son anniversaire).",
    "Fais le slow le plus dramatique de l'histoire avec le joueur de ton choix.",
    "Dis à chaque joueur ce que tu pensais d'eux la première fois.",
    "Fais un toast émouvant de 30 secondes à la soirée.",
    "Fais 20 secondes de stand-up sur le joueur à ta gauche.",
    "Laisse le joueur de ton choix t'envoyer un défi en message privé (que tu dois faire).",
    "Mange quelque chose de la cuisine choisi par le groupe.",
    "Fais une imitation de ta mère qui te gronde.",
    "Fais un selfie ridicule avec le joueur de ton choix et envoie-le au groupe.",
    "Danse sur la prochaine chanson comme si c'était ton dernier jour sur terre.",
    "Lis à voix haute le dernier message que tu as envoyé.",
    "Fais un massage d'épaules de 20 secondes au joueur à ta droite.",
    "Garde un glaçon dans ta main jusqu'à ce qu'il fonde (ou bois 3 gorgées).",
    "Laisse le groupe choisir ta prochaine photo de profil (pendant 24 h).",
    "Fais une impro de 30 secondes : tu es un serveur dans un resto chic.",
    "Fais 3 compliments drôles et 1 critique gentille au joueur de ton choix.",
    "Raconte ton plus gros râteau.",
    "Imite un joueur de la soirée pendant tout un tour, les autres doivent deviner.",
    "Fais une demande en mariage à genoux au joueur de ton choix.",
    "Fais une battle de danse contre le joueur de ton choix, le groupe vote.",
    "Bois en équilibre sur une jambe.",
    "Avoue ton plus gros crush de célébrité et défends ton choix 20 secondes.",
    "Laisse quelqu'un regarder tes 10 derniers likes Instagram.",
    "Fais un discours pour convaincre le groupe que tu es le meilleur joueur.",
    "Chante en remplaçant toutes les paroles par « bière »."
  ],
  Chaos: [
    "Laisse le groupe envoyer un message de ton choix (validé à la majorité) à ton ex ou à ton crush… ou bois 4 gorgées.",
    "Échange ton haut avec le joueur de ton choix jusqu'à la fin de la partie.",
    "Laisse quelqu'un faire défiler ta galerie pendant 10 secondes.",
    "Fais un lap dance comique de 15 secondes à une chaise.",
    "Appelle un ami au hasard et dis-lui que tu as un secret énorme à lui révéler… puis raccroche.",
    "Lis à voix haute ta dernière note sur ton téléphone.",
    "Fais un body shot ou laisse quelqu'un en faire un sur ton bras.",
    "Fais une imitation de chaque joueur en 5 secondes chacun.",
    "Laisse le joueur à ta gauche répondre à ton prochain message à ta place.",
    "Enlève une chaussette et donne-la au joueur de ton choix jusqu'à la fin.",
    "Bois un mélange préparé par le groupe (sans danger, petite quantité).",
    "Avoue qui ici tu trouves le plus attirant (ou bois 4 gorgées).",
    "Fais un strip-tease d'un seul accessoire (montre, bague, veste…) avec musique.",
    "Embrasse la main du joueur de ton choix comme un chevalier.",
    "Fais un dance-off contre tout le monde à la fois.",
    "Laisse le groupe changer ton nom dans le contact de quelqu'un (avec son accord).",
    "Raconte ton moment le plus honteux en soirée sans rien censurer.",
    "Fais une déclaration d'amour au joueur à ta droite en le regardant dans les yeux 20 secondes.",
    "Mets ton verre sur ta tête pendant un tour (ou bois-le).",
    "Mime un orgasme… de joie en mangeant un plat délicieux.",
    "Envoie un vocal où tu chantes une chanson d'amour à la 3e personne de ta conversation récente.",
    "Laisse le groupe poser n'importe quelle question : tu dois répondre « oui » ou « non » sans mentir.",
    "Fais la danse du ventre pendant 15 secondes.",
    "Bois 2 gorgées à chaque fois que quelqu'un dit ton prénom pendant un tour.",
    "Laisse le joueur de ton choix te maquiller pendant 1 minute.",
    "Fais un câlin à tout le monde, un par un, en disant un secret à l'oreille de chacun.",
    "Appelle le dernier numéro appelé et parle-lui en accent pendant 30 secondes.",
    "Montre ton historique de recherches YouTube.",
    "Fais une imitation de toi en train de draguer.",
    "Joue à la statue : reste figé pendant que le groupe te met dans 3 positions.",
    "Garde les yeux fermés jusqu'à ton prochain tour (on te guide).",
    "Fais une course de cul sec contre le joueur de ton choix (verre d'eau pour les sages).",
    "Laisse quelqu'un écrire un mot sur ton bras au feutre.",
    "Fais la toupie 10 fois sur toi-même puis marche droit.",
    "Laisse le groupe choisir une photo de toi gênante à mettre en fond d'écran.",
    "Raconte ton rêve le plus bizarre avec tous les détails.",
    "Fais le chien qui réclame à manger auprès de chaque joueur.",
    "Danse collé-serré avec le joueur de ton choix pendant un refrain.",
    "Laisse la personne à ta gauche choisir ta prochaine boisson.",
    "Dis honnêtement ce que tu changerais chez chaque joueur.",
    "Fais un tour de la pièce sur le dos de quelqu'un (ou porte quelqu'un).",
    "Sois l'esclave du joueur de ton choix pendant un tour (dans la limite du raisonnable).",
    "Fais 30 secondes de pole dance sur un poteau imaginaire.",
    "Avoue le dernier mensonge que tu as dit à quelqu'un ici.",
    "Laisse le groupe lire tes 5 derniers messages avec la personne de ton choix.",
    "Fais une chorégraphie sexy sur une musique de dessin animé.",
    "Imite un bébé qui fait un caprice pendant 20 secondes.",
    "Mange une cuillère d'un condiment choisi par le groupe.",
    "Fais une sieste de 30 secondes sur les genoux du joueur de ton choix.",
    "Laisse quelqu'un t'appeler par un surnom honteux pour le reste de la soirée."
  ],
  Hardcore: [
    "Laisse le groupe envoyer un message (validé à la majorité) à la personne de ton choix… ou cul sec.",
    "Bois un shot sans les mains.",
    "Laisse le joueur de ton choix fouiller ton téléphone pendant 30 secondes (tu peux bloquer une appli).",
    "Fais un body shot sur le joueur qui accepte.",
    "Avoue ton plus gros secret de soirée ou prends 2 shots.",
    "Échange ton pantalon ou ta jupe avec le joueur qui accepte (ou cul sec).",
    "Appelle ton ex et dis-lui « tu avais raison » puis raccroche (ou 2 shots).",
    "Laisse le groupe poster une story choisie à la majorité sur ton compte.",
    "Fais un strip-tease de 2 vêtements (raisonnables) en musique.",
    "Bois un mélange préparé par 3 joueurs différents.",
    "Embrasse le joueur de ton choix sur la joue en le regardant dans les yeux.",
    "Dis qui ici tu embrasserais, épouserais, éviterais.",
    "Lis à voix haute le message le plus gênant de ta dernière conversation.",
    "Laisse le joueur à ta droite liker 3 vieilles photos du compte de ton choix.",
    "Fais un lap dance de 20 secondes au joueur qui accepte (ou à une chaise si personne).",
    "Bois un shot à chaque refus d'un défi jusqu'à la fin du tour.",
    "Raconte ta pire nuit en soirée sans rien omettre.",
    "Laisse le groupe choisir une personne à qui tu envoies « je pense à toi ».",
    "Fais une course de cul sec contre le joueur de ton choix.",
    "Mets ta tête sous l'eau froide pendant 5 secondes.",
    "Montre ta conversation la plus récente avec ton crush.",
    "Embrasse ton reflet dans un miroir passionnément pendant 10 secondes.",
    "Laisse quelqu'un te raser… une ligne imaginaire de sourcil au feutre.",
    "Fais 20 pompes ou bois un shot.",
    "Garde un glaçon dans ton t-shirt jusqu'à ce qu'il fonde.",
    "Donne ton téléphone déverrouillé au groupe pendant 1 minute (sans galerie).",
    "Choisis quelqu'un qui doit boire 3 gorgées à chaque fois que tu bois, jusqu'à la fin.",
    "Fais une déclaration à la personne la plus inattendue de ta liste de contacts.",
    "Bois une gorgée de chaque verre de la table.",
    "Laisse le groupe te poser 3 questions : réponds à toutes sans mentir.",
    "Fais une imitation de toi au réveil après une soirée.",
    "Danse sur la table (si elle est solide) pendant un refrain.",
    "Fais le défi « cul sec de ton verre » sans t'arrêter.",
    "Avoue ce que tu as fait de pire à quelqu'un ici.",
    "Appelle quelqu'un et commande une pizza imaginaire avec le plus grand sérieux.",
    "Laisse quelqu'un t'écrire un mot sur le front que tu gardes 30 minutes.",
    "Sois le serveur de tout le monde jusqu'à ton prochain tour.",
    "Montre la photo la plus gênante de ta galerie.",
    "Fais un bisou sur le front de chaque joueur.",
    "Accepte que le groupe choisisse ta prochaine boisson (même horrible).",
    "Fais un twerk contre un mur pendant 15 secondes.",
    "Enlève ton haut jusqu'à ton prochain tour (ou 2 shots).",
    "Raconte en détail ton dernier date.",
    "Joue au roi du silence : pas un mot jusqu'à ton prochain tour, chaque mot = 1 gorgée.",
    "Laisse le joueur de ton choix te donner une gifle… de chantilly (ou de rien).",
    "Fais une proposition indécente (drôle) au joueur de ton choix.",
    "Bois un shot préparé en secret par le groupe.",
    "Fais deviner ta position préférée en mimant avec un coussin.",
    "Chuchote un secret à l'oreille de quelqu'un, il décide s'il le révèle.",
    "Échange ta place, ton verre et ton prénom avec quelqu'un pour un tour."
  ]
};
