// Questions « Vérité » (par mode de soirée) et punitions. Reprises de l'ancienne version.

export const TRUTHS = {
  Chill: [
    "Quelle petite honte assumable tu caches encore ?",
    "Quel est ton dernier stalk innocent ?",
    "Quelle appli devrait te retirer ton temps d’écran ?",
    "Quelle photo de toi te fait le plus rire ?",
    "Quelle est ta pire excuse pour annuler un plan ?",
    "Quel message as-tu déjà écrit puis supprimé ?",
    "Quelle habitude bizarre fais-tu quand personne ne regarde ?",
    "Quel est ton crush fictif le plus gênant ?",
    "Quelle chanson connais-tu par cœur mais tu n’assumes pas ?",
    "Quelle est la chose la plus inutile que tu gardes ?",
    "Quelle personne ici te connaît le mieux ?",
    "Quel est ton plus gros fail de cuisine ?",
    "Quelle est ta peur la plus ridicule ?",
    "Quel est ton talent inutile ?",
    "Quelle vérité soft personne ne devinerait sur toi ?",
    "Quelle est la dernière recherche Google honteuse que tu assumes ?",
    "Quel surnom gênant as-tu déjà eu ?",
    "Quelle est ta manie la plus visible ?",
    "Quel est ton plus gros moment de malaise gentil ?",
    "Quelle est la chose la plus enfantine que tu fais encore ?",
    "Qui ici te ferait survivre sans téléphone ?",
    "Quelle est la chose que tu procrastines depuis trop longtemps ?",
    "Quel est ton pire achat impulsif ?",
    "Quelle est ta plus grosse obsession du moment ?",
    "Quelle story as-tu déjà supprimée par honte ?",
    "Quel est le truc le plus gênant dans tes notes ?",
    "Quelle est ta pire phrase de drague soft ?",
    "Quelle est ta comfort food honteuse ?",
    "Quel est ton plus gros mensonge innocent ?",
    "Quelle est ta plus grosse réaction dramatique pour rien ?",
    "Quel est le film que tu as vu le plus de fois ?",
    "Quelle est la dernière chose qui t’a fait pleurer ?",
    "Quel métier rêvais-tu de faire enfant ?",
    "Quelle célébrité aimerais-tu avoir comme meilleur ami ?",
    "Quel est ton plat que tu pourrais manger tous les jours ?",
    "Quel est ton pire souvenir d’école ?",
    "Quel est le cadeau le plus nul que tu as reçu ?",
    "Quel est le cadeau dont tu es le plus fier d’avoir offert ?",
    "Quelle est la dernière chose que tu as googlée ?",
    "Quelle série as-tu honte d’avoir regardée en entier ?",
    "Quel est ton surnom chez toi ?",
    "Quel est le pire job que tu as fait ?",
    "Quel animal serais-tu, et pourquoi ?",
    "Quelle est la chose la plus courageuse que tu aies faite ?",
    "Quel super-pouvoir choisirais-tu ?",
    "Quel est ton plus grand rêve pas encore réalisé ?",
    "Quelle est ta plus grosse bêtise d’enfance ?",
    "Quelle est la dernière chose qui t’a fait rire aux larmes ?",
    "Quel est le meilleur conseil qu’on t’a donné ?",
    "Quelle chanson te met de bonne humeur à coup sûr ?",
    "Quel est ton pire souvenir de vacances ?",
    "Quelle est ta plus grosse peur pour l’avenir ?",
    "Quel objet sauverais-tu en premier en cas d’incendie ?",
    "À quel personnage de série ressembles-tu le plus ?",
    "Quel est ton premier souvenir ?",
    "Quelle est la chose la plus folle que tu ferais avec un million d’euros ?",
    "Quelle est ta routine du dimanche idéal ?",
    "Quel est ton plus gros fou rire en public ?",
    "Quelle est l’appli que tu ouvres le plus ?",
    "Quel est le compliment qui t’a le plus touché ?",
    "Quelle est ta plus grosse dépense inutile ce mois-ci ?",
    "Quel est le livre ou le film qui t’a marqué ?",
    "Si tu pouvais revivre une journée, laquelle ?",
    "Quel est ton talent caché ?",
    "Quel est le prénom que tu donnerais à ton futur animal ?",
    "Quelle est ta mauvaise habitude que tu n’arrives pas à lâcher ?",
    "Qui était ton crush d’enfance ?",
    "Quel est le pire cadeau que tu as fait à quelqu’un ?",
    "Quelle est la chose la plus bizarre que tu aies mangée ?",
    "Quelle époque aurais-tu aimé vivre ?",
    "Quel est ton pire look d’adolescent ?",
    "Quelle est ta plus grande fierté ?",
    "Quel est le pire film que tu aies vu au cinéma ?",
    "Quel est ton rituel avant de dormir ?",
    "Qui dans ta famille te ressemble le plus ?",
    "Quel est le pays que tu rêves de visiter ?",
    "Quelle est la chose que tu ne sais toujours pas faire à ton âge ?",
    "Quelle est ta chanson de karaoké ?",
    "Quel est le meilleur moment de ta semaine ?",
    "Quel est ton jeu vidéo préféré de tous les temps ?",
    "Quelle est la phrase que tu dis tout le temps ?",
    "Quel est ton pire moment de stress ?",
    "Quelle est la dernière fois où tu as menti à tes parents ?",
    "Quel est le prof qui t’a le plus marqué ?",
    "Quelle est la chose que tu aimerais apprendre cette année ?",
    "Quel est ton dessin animé d’enfance préféré ?",
    "Quel est ton pire coup de soleil ?",
    "Quelle est la chose la plus gentille qu’un inconnu ait faite pour toi ?",
    "Quelle est l’odeur qui te rappelle ton enfance ?",
    "Quel est le meilleur concert que tu aies vu ?",
    "Quelle est la plus grosse dispute que tu as eue pour rien ?",
    "Quel est le pire déguisement que tu aies porté ?",
    "Quel est le meilleur repas de ta vie ?",
    "Quelle est la qualité que tu préfères chez toi ?",
    "Quel est le défaut que tu détestes chez toi ?",
    "Quelle est la chose qui t’énerve le plus chez les autres ?",
    "Quelle est la plus longue nuit blanche que tu aies faite ?",
    "Quel est ton moment préféré avec quelqu’un de ce groupe ?",
    "Quelle est ta plus grosse addiction (non alcoolisée) ?",
    "Quel est le dernier mensonge que tu as dit ?",
  ],
  Party: [
    "Quel est ton dernier message envoyé après minuit que tu regrettes ?",
    "Qui ici pourrait te faire craquer en soirée ?",
    "Quelle est ta pire décision prise bourré ?",
    "Quel est le truc le plus gênant que tu as fait en soirée ?",
    "Quelle personne as-tu déjà voulu embrasser sans oser ?",
    "Quelle est ta technique de drague la plus nulle ?",
    "Quel est ton pire lendemain de soirée ?",
    "Quelle est la personne que tu as voulu recontacter bourré ?",
    "Quel est ton plus gros mensonge pour sortir ?",
    "Quelle est ta pire story postée en soirée ?",
    "Quel est ton meilleur souvenir flou ?",
    "Quelle chanson te transforme en menace sur la piste ?",
    "Qui ici serait ton meilleur wingman ?",
    "Quelle est ta pire excuse après un date ?",
    "Quel est le truc le plus cringe que tu as dit à quelqu’un qui te plaisait ?",
    "Quelle soirée ne peux-tu pas raconter à tes parents ?",
    "Qui ici pourrait te convaincre de faire un after ?",
    "Quel est ton plus gros flirt raté ?",
    "Quelle est ta pire danse de soirée ?",
    "Quel est ton plus gros moment de confiance injustifiée ?",
    "Quel est ton pire date ?",
    "Quelle est la phrase la plus bourrée que tu as déjà dite ?",
    "Quel est ton plus gros regret de soirée ?",
    "Qui ici serait le pire partenaire d’after ?",
    "Quelle est la pire personne à qui tu as envoyé un message bourré ?",
    "Quel est ton plus gros moment de jalousie en soirée ?",
    "Quel est ton record de mauvaises décisions en une nuit ?",
    "Quelle est la chose la plus cringe que tu as faite pour attirer l’attention ?",
    "Quelle est ta pire tentative de danse sexy ?",
    "Quel est le truc le plus gênant qu’on pourrait trouver dans tes DM ?",
    "Quel est ton pire râteau ?",
    "Qui ici a le meilleur style vestimentaire ?",
    "Quelle est la soirée la plus folle que tu aies faite ?",
    "Quelle est ta boisson préférée en soirée, et ta pire ?",
    "Qui ici danse le mieux… et qui danse le pire ?",
    "Quel est le meilleur after que tu aies fait ?",
    "Quelle est ta technique pour séduire quelqu’un en soirée ?",
    "Quelle est la pire excuse que tu as donnée pour partir d’une soirée ?",
    "Quelle est la personne la plus célèbre que tu aies croisée en soirée ?",
    "Quel est ton premier souvenir de soirée ?",
    "Quel est le pire endroit où tu as dragué quelqu’un ?",
    "As-tu déjà embrassé quelqu’un dont tu ne connaissais pas le prénom ?",
    "Quel est ton record de nuit sans dormir ?",
    "Quelle chanson te fait monter sur une table ?",
    "Qui ici est le plus drôle bourré ?",
    "Qui ici est le plus pénible bourré ?",
    "Quel est ton pire premier rendez-vous ?",
    "Quel est le meilleur premier rendez-vous que tu aies eu ?",
    "Quelle est ta pire honte en boîte de nuit ?",
    "As-tu déjà été jaloux en soirée ? Raconte.",
    "Quelle est la chose la plus romantique qu’on ait faite pour toi ?",
    "Qui ici pourrait être ton date idéal ?",
    "Quelle est la pire photo de toi en soirée ?",
    "Quelle est la phrase de drague que tu as déjà utilisée sans honte ?",
    "Quel est ton type de personne idéal ?",
    "Quelle est ta plus grosse red flag en date ?",
    "Quel est le pire message que tu as reçu d’un crush ?",
    "As-tu déjà menti sur ton âge en soirée ?",
    "Quel est le pire cocktail que tu aies goûté ?",
    "Quel est ton plus gros fou rire en soirée ?",
    "As-tu déjà dormi chez quelqu’un que tu connaissais à peine ?",
    "Quelle est la pire chose que tu aies faite pour rentrer dans une boîte ?",
    "Quelle est ta plus grosse folie en vacances ?",
    "As-tu déjà eu un crush sur quelqu’un de ce groupe ?",
    "Qui ici a le meilleur rire ?",
    "Quel est le meilleur compliment que tu aies reçu en soirée ?",
    "Quelle est la personne la plus improbable avec qui tu aies dansé ?",
    "As-tu déjà pleuré en soirée ? Pourquoi ?",
    "Quelle est la dernière personne qui t’a envoyé un message coquin ?",
    "As-tu déjà été le dernier à quitter une soirée ?",
    "Quel est le pire karaoké que tu aies fait ?",
    "Quelle est ta plus belle rencontre en soirée ?",
    "Qui ici te piquerait ton crush sans hésiter ?",
    "Quelle est la chose la plus folle que tu aies faite pour quelqu’un qui te plaisait ?",
    "As-tu déjà fait semblant d’être malade pour éviter une soirée ?",
    "Quel est ton meilleur souvenir de festival ?",
    "Quelle est ta pire gueule de bois ?",
    "Quel est le message le plus gênant que tu as envoyé à un crush ?",
    "As-tu déjà dragué quelqu’un juste pour un pari ?",
    "Qui ici a le plus de chances de finir la soirée avec quelqu’un ?",
    "Quelle est ta plus grosse erreur sur une appli de rencontre ?",
    "Quel est le pire endroit où tu t’es endormi en soirée ?",
    "As-tu déjà oublié le prénom de la personne avec qui tu flirtais ?",
    "Quel est le date le plus bizarre que tu aies eu ?",
    "Qui ici aimerais-tu voir en couple ?",
    "Quelle est la pire soirée à laquelle tu as été invité ?",
    "As-tu déjà ghosté quelqu’un après un date ? Pourquoi ?",
    "Quelle chanson te rappelle un ex ?",
    "Quel est le meilleur moment de cette soirée jusqu’ici ?",
    "Avec qui ici partirais-tu en vacances sur un coup de tête ?",
    "Quelle est la plus grosse dépense que tu aies faite en une seule soirée ?",
    "Qui ici est le plus mauvais menteur ?",
    "Quelle est ta pire danse quand tu es seul ?",
    "As-tu déjà fait une déclaration d’amour en soirée ?",
    "Quelle est la chose la plus bête que tu aies dite à un videur ?",
    "Quel est ton plus gros flirt de vacances ?",
    "Qui ici te ferait le meilleur discours de mariage ?",
    "Quel est le pire déguisement que tu aies porté en soirée ?",
    "Quelle est ta pire chute en soirée ?",
    "Avec qui ici ferais-tu une colocation… et avec qui jamais ?",
  ],
  Chaos: [
    "Qui ici t’agace parfois sans le savoir ?",
    "Quel est ton plus gros mensonge récent ?",
    "Quelle vérité pourrait créer un malaise dans le groupe ?",
    "Quel secret as-tu déjà failli révéler bourré ?",
    "Quelle personne as-tu déjà ghostée sans vraie raison ?",
    "Quel est le pire truc que tu as dit sous alcool ?",
    "Quelle relation as-tu déjà sabotée tout seul ?",
    "Quel est ton plus gros red flag social ?",
    "Quelle est la chose la plus toxique que tu as déjà faite ?",
    "Quel message de toi pourrait te faire honte demain ?",
    "Quelle est ta pire opinion que tu évites de dire ?",
    "Qui ici te connaît moins bien qu’il le croit ?",
    "Quelle est la chose que tu caches le plus à tes potes ?",
    "Quel est ton plus gros moment de mauvaise foi ?",
    "Quelle personne as-tu déjà fait semblant d’aimer ?",
    "Quel est ton plus gros drama non résolu ?",
    "Quelle est ta plus grosse manipulation soft ?",
    "Quel est le pire truc que tu as déjà fait par jalousie ?",
    "Quelle confession pourrait changer l’ambiance ?",
    "Qui ici pourrait découvrir un truc bizarre sur toi ?",
    "Quelle promesse n’as-tu jamais tenue ?",
    "Quel est ton plus gros mensonge par omission ?",
    "Quelle conversation supprimerais-tu en premier ?",
    "Quel est ton plus gros acte de lâcheté sociale ?",
    "Quelle personne as-tu déjà stalkée beaucoup trop longtemps ?",
    "Quelle est ta pire excuse pour disparaître ?",
    "Quel est ton plus gros moment de honte relationnelle ?",
    "Qui ici aurait le plus de dossiers sur toi ?",
    "Quelle est ta pire décision prise pour plaire ?",
    "Quel est le truc le plus problématique dans ton historique ?",
    "Qui ici te fait le plus rire… et qui te fait le moins rire ?",
    "Quel est le secret que tu as gardé le plus longtemps ?",
    "As-tu déjà dit du mal de quelqu’un de cette pièce ?",
    "Quelle est la plus grosse dispute que tu aies eue avec un ami ici ?",
    "Qui ici a déjà eu un comportement que tu n’as pas aimé ?",
    "Quelle est ta plus grosse jalousie envers quelqu’un ici ?",
    "Qui ici te semble le plus faux ?",
    "Quel est le mensonge que tu as dit à quelqu’un ici ?",
    "As-tu déjà lu les messages de quelqu’un sans permission ?",
    "Quel est ton plus gros regret amical ?",
    "Quel est le pire conseil que tu aies donné à un ami ?",
    "As-tu déjà trahi la confiance d’un ami ?",
    "Qui ici choisirais-tu d’éliminer d’une île déserte ?",
    "Quelle est la chose que tu n’as jamais osé dire à quelqu’un ici ?",
    "Quelle est ta pire réaction en dispute ?",
    "As-tu déjà menti pour te sortir d’une situation avec un ami ici ?",
    "Qui ici a la pire influence sur toi ?",
    "Qui ici a la meilleure influence sur toi ?",
    "Quelle est l’opinion impopulaire que tu as sur quelqu’un ici ?",
    "Quelle est la chose qui te met le plus mal à l’aise chez tes potes ?",
    "Qui ici a déjà dit un truc qui t’a blessé sans le savoir ?",
    "Quel est ton plus gros défaut en amitié ?",
    "As-tu déjà été jaloux d’un ami ici pour sa relation ?",
    "Quel est le pire secret que quelqu’un t’ait confié (sans dire qui) ?",
    "Qui ici serait le premier à te trahir pour de l’argent ?",
    "Quelle est la pire chose que tu aies faite à un ex ?",
    "As-tu déjà fait semblant d’être malade pour éviter quelqu’un ici ?",
    "Qui ici écoute le moins quand on parle ?",
    "Quel est ton plus gros mensonge sur les réseaux ?",
    "As-tu déjà été content du malheur de quelqu’un ?",
    "Quel est le pire truc que tu aies pensé de quelqu’un à la première rencontre ?",
    "Qui ici as-tu mal jugé au début ?",
    "Quelle est la pire excuse que tu aies inventée pour annuler avec quelqu’un ici ?",
    "As-tu déjà voulu quitter ce groupe d’amis ?",
    "Qui ici te rend le plus jaloux, et pourquoi ?",
    "Quel est le compliment que tu n’as jamais fait à quelqu’un ici ?",
    "Quelle est la plus grosse erreur de ta vie ?",
    "As-tu déjà regretté d’avoir présenté quelqu’un ici à un de tes potes ?",
    "Qui ici serait le pire colocataire ?",
    "Quel est le plus gros drama que tu aies provoqué ?",
    "Quelle conversation de groupe aimerais-tu que personne ne lise ?",
    "As-tu déjà fait une capture d’écran d’une conversation pour la montrer ?",
    "Qui ici a le plus changé depuis que tu le connais ?",
    "Quel est le pire cadeau qu’on t’ait fait ici ?",
    "As-tu déjà stalké l’ex d’un ami ?",
    "Qui ici crois-tu qu’il parle de toi dans ton dos ?",
    "Quelle est la limite que tu ne pardonnerais jamais à un ami ?",
    "As-tu déjà menti pour couvrir un ami ?",
    "Qui ici appellerais-tu en premier si tu avais un problème ?",
    "Qui ici n’appellerais-tu jamais en cas de problème ?",
    "Quelle est ta plus grosse hypocrisie ?",
    "Quel est le truc le plus égoïste que tu aies fait ?",
    "As-tu déjà oublié volontairement l’anniversaire de quelqu’un ?",
    "Quelle est la pire rumeur que tu aies lancée ou crue ?",
    "Qui ici a la pire hygiène de vie ?",
    "Quel est le pire défaut de ton meilleur ami ?",
    "As-tu déjà eu envie d’embrasser quelqu’un en couple ?",
    "Qui ici te doit encore de l’argent ?",
    "Quel est le pire sujet de dispute de ton couple actuel ou passé ?",
    "Quelle est la chose la plus mesquine que tu aies faite ?",
    "As-tu déjà pris le parti de quelqu’un ici juste pour éviter un drama ?",
    "Qui ici serait capable de garder ton pire secret ?",
    "Quel est le reproche que tu aimerais faire au groupe ?",
    "As-tu déjà fait semblant de ne pas voir un message de quelqu’un ici ?",
    "Qui ici aimerais-tu mieux connaître ?",
    "Quel est ton plus gros coup de gueule de l’année ?",
    "Quelle est la chose que tu changerais chez quelqu’un ici si tu pouvais ?",
    "As-tu déjà menti dans ce jeu ?",
  ],
  Hardcore: [
    "Quel secret ne veux-tu vraiment pas que le groupe découvre ?",
    "Quelle est ta pire trahison amicale ou amoureuse ?",
    "As-tu déjà trompé quelqu’un ou aidé quelqu’un à tromper ?",
    "Quel est ton plus gros regret intime ?",
    "Quel est ton kink le plus difficile à assumer ?",
    "Quelle relation de ton passé te ferait honte aujourd’hui ?",
    "Quel est le truc le plus immoral que tu as fait par désir ?",
    "Quelle personne ici te trouble plus que tu ne l’assumes ?",
    "Quelle vérité pourrait te faire perdre des points auprès du groupe ?",
    "Quel est ton plus gros mensonge dans une relation ?",
    "As-tu déjà caché une double vie sentimentale ou sexuelle ?",
    "Quelle est la pire chose que tu as faite pour être désiré ?",
    "Quel message supprimé te ferait le plus paniquer ?",
    "Quel est ton plus gros moment de honte après une soirée ?",
    "Quelle est ta limite que tu as déjà franchie ?",
    "Quel fantasme ne veux-tu pas expliquer à voix haute ?",
    "Quel est ton plus gros comportement toxique en amour ?",
    "Quelle personne as-tu déjà utilisée affectivement ?",
    "Quel est ton plus gros mensonge sur ton passé ?",
    "Quelle vérité sur ton téléphone te ferait transpirer ?",
    "As-tu déjà menti sur ton nombre de partenaires ?",
    "Quel est ton pire choix de partenaire ?",
    "Quelle est la chose que tu regrettes d’avoir envoyée ?",
    "Quel secret intime as-tu déjà gardé trop longtemps ?",
    "Quelle est ta pire excuse après avoir blessé quelqu’un ?",
    "Quel est ton plus gros moment de désir honteux ?",
    "Quelle décision sexuelle ou romantique referais-tu jamais ?",
    "Quel est le truc le plus sale émotionnellement que tu as déjà fait ?",
    "Quelle personne du passé pourrait te ruiner l’ambiance ?",
    "Quelle vérité te ferait choisir de boire direct ?",
    "Quel est ton pire blackout en soirée ?",
    "Quelle est la chose la plus stupide que tu as faite bourré ?",
    "As-tu déjà vomi dans un endroit honteux ?",
    "Quel est ton plus gros regret après une soirée ?",
    "Quel message bourré regrettes-tu le plus ?",
    "As-tu déjà appelé quelqu’un totalement ivre ?",
    "Quel est ton pire mélange d’alcool ?",
    "As-tu déjà oublié une soirée entière ?",
    "Quel est le pire endroit où tu t’es réveillé après une soirée ?",
    "Quelle est ta pire honte devant des inconnus en étant bourré ?",
    "As-tu déjà cassé quelque chose en soirée ?",
    "Quel est ton plus gros mensonge pour rentrer de soirée ?",
    "As-tu déjà été refusé en boîte ?",
    "Quel est ton pire fail en essayant d’impressionner quelqu’un bourré ?",
    "Quelle est la pire odeur/sensation de lendemain de soirée ?",
    "As-tu déjà dormi dehors après une soirée ?",
    "Quel est ton record de shots approximatif ?",
    "Quel est le pire alcool que tu ne peux plus voir ?",
    "As-tu déjà confondu quelqu’un en étant bourré ?",
    "Quel est ton moment le plus gênant en boîte ?",
    "As-tu déjà envoyé un vocal catastrophique bourré ?",
    "Quel est ton pire Uber/taxi retour de soirée ?",
    "As-tu déjà perdu ton téléphone/portefeuille en soirée ?",
    "Quelle est la pire excuse que tu as donnée après une soirée ?",
    "As-tu déjà été sick après seulement quelques verres ?",
    "Quel est le truc le plus absurde que tu as acheté bourré ?",
    "As-tu déjà dansé de façon honteuse sans t’en rendre compte ?",
    "Quelle personne ici serait la pire à gérer bourrée ?",
    "As-tu déjà oublié où tu habitais en rentrant ?",
    "Quel est le moment où tu t’es dit : 'je suis allé trop loin' ?",
    "As-tu déjà été ami avec quelqu’un juste le temps d’une soirée ?",
    "Quel est ton plus gros fail de préchauffe ?",
    "Quelle est la pire boisson qu’on t’a forcé à goûter ?",
    "As-tu déjà parlé une autre langue en étant bourré ?",
    "Quel est ton plus gros exploit alcoolisé ?",
    "As-tu déjà dormi avec tes vêtements de soirée plusieurs jours ?",
    "Quel est ton pire combo alcool + nourriture ?",
    "As-tu déjà tenté un défi débile sous alcool ?",
    "Quelle est la pire phrase que tu as dite bourré ?",
    "Quel est ton fantasme le plus inavouable (dans les limites du raisonnable) ?",
    "Qui ici embrasserais-tu si tu étais obligé ?",
    "Quel est l’endroit le plus insolite où tu aies fait l’amour ?",
    "As-tu déjà eu un coup d’un soir ? Raconte le meilleur ou le pire.",
    "Quel est ton body count, à peu près ?",
    "As-tu déjà simulé ?",
    "Quel est le meilleur coup que tu aies eu, sans dire qui ?",
    "As-tu déjà envoyé un nude ? Et à la mauvaise personne ?",
    "Quelle est la chose qui t’attire le plus physiquement chez quelqu’un ?",
    "As-tu déjà fait un plan à trois, ou en as-tu envie ?",
    "Qui ici a le plus de chances d’être un bon coup, selon toi ?",
    "Quel est ton plus gros fail au lit ?",
    "Quelle est la chose la plus coquine que tu aies faite en public ?",
    "As-tu déjà été surpris en pleine action ?",
    "Quel est le date qui a le plus vite fini au lit ?",
    "As-tu déjà couché avec quelqu’un juste pour oublier un ex ?",
    "Quelle est la célébrité avec qui tu passerais une nuit ?",
    "As-tu déjà eu une relation avec quelqu’un beaucoup plus âgé ?",
    "Quel est le message le plus chaud que tu aies envoyé ?",
    "As-tu déjà eu un plan cul qui a tourné en histoire d’amour ?",
    "Quelle est la pire excuse que tu aies donnée pour ne pas rester dormir ?",
    "As-tu déjà eu un crush sur le partenaire d’un ami ?",
    "Quel est ton plus gros secret de couple ?",
    "As-tu déjà trompé, ou été trompé ? Raconte.",
    "Quelle est la chose la plus folle que tu aies faite par jalousie ?",
    "As-tu déjà eu une relation cachée ?",
    "Qui ici serait le pire en couple ?",
    "Qui ici serait le meilleur en couple ?",
    "As-tu déjà dragué un ex de quelqu’un ici ?",
    "Quelle est la plus longue période sans relation ?",
    "Quel est ton jouet ou accessoire préféré, si tu en as un ?",
    "As-tu déjà regardé des vidéos coquines avec quelqu’un ?",
    "Quelle est ta position préférée, en un mot ?",
  ],
};
