// Noms français des œuvres du Blind test (films, séries, dessins animés, Disney, jeux vidéo).
// Deezer donne souvent le titre anglais, ou le nom de la chanson au lieu du film :
// cette table ramène chaque réponse au nom de l'œuvre tel qu'on le connaît en France.
// Clé = réponse brute en minuscules ; valeur = nom affiché, ou null pour écarter le morceau
// (titre impossible à deviner). Une réponse absente de la table est gardée telle quelle,
// sauf pour les thèmes « strict » (Disney) où seules les réponses connues sont gardées.

const SKIP = null;

export const FR_NAMES = {
  // ---------- Films ----------
  "...baby one more time": SKIP,
  "\"jumanji\"": "Jumanji",
  "2001 odyssée de l'espace": "2001, l'Odyssée de l'espace",
  "a la poursuite du diamant vert": "À la poursuite du diamant vert",
  "a thousand miles (interlude)": "F.B.I. Fausses Blondes Infiltrées",
  "alabina (la vérité si je mens)": "La vérité si je mens !",
  "bad day": "Alvin et les Chipmunks",
  "bibbidi-bobbidi-boo": "Cendrillon",
  "can you feel the love tonight": "Le Roi lion",
  "chanson sur une drôle de vie": SKIP,
  "crowd control": SKIP,
  "cuban pete": "The Mask",
  "des gammes et des arpèges": "Les Aristochats",
  "despicable me 4": "Moi, moche et méchant 4",
  "dîner de cons": "Le Dîner de cons",
  "do your thing": SKIP,
  "e.t.": "E.T. l'extra-terrestre",
  "enae volare": SKIP,
  "enfant de l'homme": "Tarzan",
  "être un homme comme vous": "Le Livre de la jungle",
  "friend medley": SKIP,
  "ghostbusters": "SOS Fantômes",
  "give me the night": SKIP,
  "go team!": SKIP,
  "good life": SKIP,
  "hair up": "Les Trolls",
  "hakuna matata": "Le Roi lion",
  "he's a pirate": "Pirates des Caraïbes",
  "holiday": SKIP,
  "home": SKIP,
  "home alone": "Maman, j'ai raté l'avion !",
  "how far i'll go": "Vaiana",
  "i like to move it": "Madagascar",
  "i'm alive": "Stuart Little 2",
  "il en faut peu pour être heureux": "Le Livre de la jungle",
  "independance day": "Independence Day",
  "intouchables (una mattina)": "Intouchables",
  "invente ta route": SKIP,
  "je veux savoir": "Tarzan",
  "je voudrais déjà être roi": "Le Roi lion",
  "jurassic parc ii": "Le Monde perdu : Jurassic Park",
  "just because of you (come on my love)": SKIP,
  "key of life": SKIP,
  "kirikou, l'enfant monde": "Kirikou et la Sorcière",
  "kiss the sky": "Le Robot sauvage",
  "kung fu fighting (celebration time)": "Kung Fu Panda",
  "l'amour brille sous les étoiles": "Le Roi lion",
  "l'histoire de la vie": "Le Roi lion",
  "la 7ème compagnie": "Mais où est donc passée la 7e compagnie ?",
  "la marche des gendarmes": "Le Gendarme de Saint-Tropez",
  "la reine des neiges": "La Reine des neiges",
  "la boum": "La Boum",
  "les mondes engloutis": "Les Mondes engloutis",
  "big bang theory": "The Big Bang Theory",
  "la soupe aux choux": "La Soupe aux choux",
  "la vie est belle": "La vie est belle",
  "lava": SKIP,
  "le bleu lumière": "Vaiana",
  "le cinquième element": "Le Cinquième Élément",
  "le cœur de glace": "La Reine des neiges",
  "le grand bleu (thème du film)": "Le Grand Bleu",
  "le parrain": "Le Parrain",
  "le pic de dante": "Le Pic de Dante",
  "le silence des agneaux": "Le Silence des agneaux",
  "les aventures de rabbi jacob": "Les Aventures de Rabbi Jacob",
  "les dents de la mer": "Les Dents de la mer",
  "les incorruptibles": "Les Incorruptibles",
  "looking for clues": SKIP,
  "mamma mia": "Mamma Mia !",
  "mission impossible": "Mission impossible",
  "mon coeur fait vroum (my heart goes vroom)": SKIP,
  "move your feet / d.a.n.c.e. / it's a sunshine day": "Les Trolls",
  "neuf semaine et demi": "9 semaines ½",
  "never ending story": "L'Histoire sans fin",
  "night at the museum": "La Nuit au musée",
  "notre paradis": SKIP,
  "nuits d'arabie": "Aladdin",
  "oogie boogie's song": "L'Étrange Noël de monsieur Jack",
  "opening travel music": SKIP,
  "orange mécanique": "Orange mécanique",
  "pat'patrouille : mission dino": "La Pat'Patrouille",
  "phantom manor medley": SKIP,
  "pump it": SKIP,
  "pursuit of happiness": SKIP,
  "retour vers le futur": "Retour vers le futur",
  "right round": SKIP,
  "snow white and the seven dwarfs": "Blanche-Neige et les Sept Nains",
  "squeeze me": SKIP,
  "suite from x2": "X-Men 2",
  "supercalifragilisticexpialidocious": "Mary Poppins",
  "tennessee": "Pearl Harbor",
  "terminated": SKIP,
  "the bodyguard": "Bodyguard",
  "the bridge of khazad dum": "Le Seigneur des anneaux",
  "the chronicles of narnia": "Le Monde de Narnia",
  "the day after tomorrow": "Le Jour d'après",
  "the exorcist": "L'Exorciste",
  "the hunger games": "Hunger Games",
  "the matrix - main title theme - clubbed to death (ringtone, pt. 2)": "Matrix",
  "the mummy returns": "Le Retour de la momie",
  "the right kind of wrong": "Coyote Girls",
  "the shining": "Shining",
  "top gun (anthem)": "Top Gun",
  "trolls": "Les Trolls",
  "un poco loco": "Coco",
  "unforgettable": SKIP,
  "what time is it": "High School Musical 2",
  "while my guitar gently weeps": SKIP,
  "wonderful life (mi oh my)": SKIP,
  "yellow light": SKIP,
  "zimmer: main theme [rain man]": "Rain Man",
  "zorro's theme (instrumental)": "Zorro",

  // ---------- Séries & génériques TV ----------
  "\"quotidien quotidien\" le jt de tf1": "Le JT de TF1",
  "90210 beverly hills": "Beverly Hills 90210",
  "agence tous risques": "L'Agence tous risques",
  "all star": "Shrek",
  "astérix le gaulois: thème d'astérix": "Astérix le Gaulois",
  "au pays de candy": "Candy",
  "autant en emporte le vent": "Autant en emporte le vent",
  "boss of me": "Malcolm",
  "capitaine flam: la chevauchée du capitaine flam": "Capitaine Flam",
  "capitaine flam - cap'tain flam": "Capitaine Flam",
  "dance with wolves": "Danse avec les loups",
  "eye of the tiger": "Rocky III",
  "flying from \"e.t. the extra-terrestrial\"": "E.T. l'extra-terrestre",
  "goldorak : la légende d'actarus": "Goldorak",
  "goldorak : et l'aventure continue": "Goldorak",
  "happy meal (concerto pour l'aile ou la cuisse)": "L'Aile ou la Cuisse",
  "harry potter and the philosopher's stone": "Harry Potter à l'école des sorciers",
  "harry potter and the philospher's stone - harry's wonderful world": "Harry Potter à l'école des sorciers",
  "hawaï police d'etat": "Hawaï police d'État",
  "i don't want to be": "Les Frères Scott",
  "i don't want to miss a thing": "Armageddon",
  "la chanson d'heidi": "Heidi",
  "la chanson de belle et sébastien": "Belle et Sébastien",
  "la famille des barbapapa": "Barbapapa",
  "la guerre des étoiles": "Star Wars",
  "la météo sur tf1": "La météo de TF1",
  "la panthère rose": "La Panthère rose",
  "le 13 heures de mourousi": "Le 13 heures de TF1",
  "le bon, la brute et le truand": "Le Bon, la Brute et le Truand",
  "le clan des siciliens": "Le Clan des Siciliens",
  "le grand blond avec une chaussure noire": "Le Grand Blond avec une chaussure noire",
  "le pont de la rivière kwai": "Le Pont de la rivière Kwaï",
  "le roi lion": "Le Roi lion",
  "les chariots de feu": "Les Chariots de feu",
  "les dossiers de l'écran (spirituals for strings choir and orchestra: iv. protest)": "Les Dossiers de l'écran",
  "les entrechats sont là!": "Les Entrechats",
  "lawrence d'arabie": "Lawrence d'Arabie",
  "ma sorcière bien aimée": "Ma sorcière bien-aimée",
  "married life": "Là-haut",
  "maya l'abeille (die biene maja)": "Maya l'abeille",
  "monsters, inc.": "Monstres et Cie",
  "pirates of the caribbean": "Pirates des Caraïbes",
  "pokémon (attrapez-les tous !)": "Pokémon",
  "rabbi jacob: danse de la joie": "Les Aventures de Rabbi Jacob",
  "reality": "La Boum",
  "rencontre du troisième type": "Rencontres du troisième type",
  "signé cat's eyes": "Cat's Eyes",
  "soldiers": SKIP,
  "sweet home alabama": SKIP,
  "the fresh prince of bel-air - the theme music": "Le Prince de Bel-Air",
  "the simpsons theme (single)": "Les Simpson",
  "titles from chariots of fire": "Les Chariots de feu",
  "tom sawyer: le petit monde de tom sawyer": "Tom Sawyer",
  "tuyo": "Narcos",
  "ulysse revient": "Ulysse 31",
  "voici venir les babapapa": "Barbapapa",
  "voici venir les barbapapa": "Barbapapa",
  "x files": "X-Files",

  // ---------- Dessins animés ----------
  "albator, le corsaire de l'espace": "Albator",
  "batman the animated series (1996)": "Batman",
  "ben 10 - theme song": "Ben 10",
  "beyblade metal fusion": "Beyblade",
  "bioman est de retour": "Bioman",
  "bioman: dis moi bioman": "Bioman",
  "dis-moi bioman": "Bioman",
  "bouba, le petit ourson": "Bouba le petit ourson",
  "candy s'endort": "Candy",
  "la chanson de candy": "Candy",
  "clifford the big red dog - main": "Clifford",
  "denver": "Denver, le dernier dinosaure",
  "denver le dernier dinosaure": "Denver, le dernier dinosaure",
  "dora the explorer": "Dora l'exploratrice",
  "dragon ball et dragon ball z": "Dragon Ball Z",
  "droles de dames": "Drôles de dames",
  "g.i. joe (toujours au combat)": "G.I. Joe",
  "génération foot 2 rue": "Foot 2 rue",
  "gormiti che miti": "Gormiti",
  "gravity falls main title": "Souvenirs de Gravity Falls",
  "here we go - totally spies": "Totally Spies!",
  "hey arnold": "Hé Arnold !",
  "jimmy neutron boy genius": "Jimmy Neutron",
  "k 2000": "K 2000",
  "k2000": "K 2000",
  "krypto the superdog": "Krypto le superchien",
  "la ballade d'actarus": "Goldorak",
  "la justice de goldorak": "Goldorak",
  "le retour de goldorak": "Goldorak",
  "la chanson de lamu": "Lamu",
  "la chanson de mon petit poney": "Mon petit poney",
  "la chanson des chevaliers": "Les Chevaliers du Zodiaque",
  "la chanson des chevaliers (les chevaliers du zodiaque)": "Les Chevaliers du Zodiaque",
  "les chevaliers du zodiaque": "Les Chevaliers du Zodiaque",
  "la cité d'or": "Les Mystérieuses Cités d'or",
  "les cités d'or": "Les Mystérieuses Cités d'or",
  "les mystérieuses cités d'or": "Les Mystérieuses Cités d'or",
  "la famille pierrafeu": "Les Pierrafeu",
  "la fête au village": SKIP,
  "la série tv": SKIP,
  "le combat des héros": SKIP,
  "le tour du monde en 80 jours (d'après l'œuvre de jules verne)": "Le Tour du monde en 80 jours",
  "les maîtres de l'univers": "Les Maîtres de l'univers",
  "musclor (les maîtres de l'univers)": "Les Maîtres de l'univers",
  "les quatres filles du docteur march": "Les Quatre Filles du docteur March",
  "main title": SKIP,
  "martin mystere": "Martin Mystère",
  "merguez partie": SKIP,
  "mission kim possible": "Kim Possible",
  "mission: impossible": "Mission impossible",
  "music from mission: impossible": "Mission impossible",
  "monster high fright song": "Monster High",
  "olive et tom": "Olive et Tom",
  "petits amis, bonjour": SKIP,
  "powerpuff girls": "Les Supers Nanas",
  "recess": "La Cour de récré",
  "rugrats - main": "Les Razmoket",
  "salut les musclés (au zénith)": "Salut les Musclés",
  "scooby doo - quoi d'neuf?": "Scooby-Doo",
  "she-ra princess of power (1985) - theme song": "She-Ra",
  "space goofs": "Les Zinzins de l'espace",
  "spectacular spider-man": "Spider-Man",
  "sponge bob square pants": "Bob l'éponge",
  "teletubbies say \"eh-oh!\"": "Les Teletubbies",
  "the adventures of tintin ringtone": "Les Aventures de Tintin",
  "the garfield show -": "Garfield",
  "the magic school bus": "Le Bus magique",
  "the wild thornberrys": "La Famille Delajungle",
  "the woody woodpecker show": "Woody Woodpecker",
  "toccata and fugue in d minor, bwv 565 - toccata": SKIP,
  "today is gonna be a great day": "Phinéas et Ferb",
  "tom and jerry": "Tom et Jerry",
  "transformers pour un monde meilleur": "Transformers",
  "un monde sans danger": "Code Lyoko",
  "wakfu: sur tes pas": "Wakfu",
  "we're magic all the way": SKIP,
  "who's the boss": "Madame est servie",
  "yu-gi-oh! season 1": "Yu-Gi-Oh!",

  // ---------- Disney : la chanson → le film ----------
  "à travers le bayou": "La Princesse et la Grenouille",
  "á upendi": "Le Roi lion 2",
  "aie confiance": "Le Livre de la jungle",
  "aladdin": "Aladdin",
  "an innocent warrior": "Vaiana",
  "au son calme des tam-tams (reprise)": "Pocahontas",
  "belle (reprise)": "La Belle et la Bête",
  "bienvenue": "Frère des ours",
  "big hero 6": "Les Nouveaux Héros",
  "blanche neige et les septs nains": "Blanche-Neige et les Sept Nains",
  "can't stop the feeling!": "Les Trolls",
  "ce rêve bleu": "Aladdin",
  "cendrillon": "Cendrillon",
  "charivari": "Le Bossu de Notre-Dame",
  "chillin' like a villain": "Descendants 2",
  "dans un autre monde": "La Reine des neiges 2",
  "de bons conseils": "La Reine des neiges",
  "de zéro en héros": "Hercule",
  "define dancing": "WALL-E",
  "des sauvages i": "Pocahontas",
  "des sauvages ii": "Pocahontas",
  "embrasse-la": "La Petite Sirène",
  "en été": "La Reine des neiges",
  "end of line": "Tron : L'Héritage",
  "entre deux mondes": "Tarzan",
  "entre deux mondes (reprise)": "Tarzan",
  "frozen": "La Reine des neiges",
  "gotta go my own way": "High School Musical 2",
  "he mele no lilo": "Lilo et Stitch",
  "heigh-ho": "Blanche-Neige et les Sept Nains",
  "hercule": "Hercule",
  "hercules": "Hercule",
  "honneur à tous": "Mulan",
  "i thought i lost you": "Volt, star malgré lui",
  "iduna's scarf": "La Reine des neiges 2",
  "il vit en toi": "Le Roi lion 2",
  "il y a longtemps..": "Anastasia",
  "j'en ai rêvé": "La Belle au bois dormant",
  "jamais je n'avouerai": "Hercule",
  "je fais le vœu": "Wish",
  "je reviens plus fort (inspiré par \"soul\")": "Soul",
  "je suis ton meilleur ami": "Aladdin",
  "je suis vaiana (le chant des ancêtres)": "Vaiana",
  "je vole": "Aladdin",
  "l'amour nous guidera": "Le Roi lion 2",
  "l'étrange noël de monsieur jack": "L'Étrange Noël de monsieur Jack",
  "l'un des nôtres": "Le Roi lion 2",
  "la belle et la bête": "La Belle et la Bête",
  "la berceuse d'ahtohallan": "La Reine des neiges 2",
  "la chanson de la pluie": "Bambi",
  "la cour des miracles": "Le Bossu de Notre-Dame",
  "la famille madrigal": "Encanto",
  "la leçon de musique/chante doux rossignol/lucifer, le vilain chat/un message de sa majesté": "Cendrillon",
  "la patrouille des éléphants": "Le Livre de la jungle",
  "la petite sirène": "La Petite Sirène",
  "la princesse et la grenouille": "La Princesse et la Grenouille",
  "la saison des fêtes": "La Reine des neiges : Joyeuses fêtes avec Olaf",
  "la saison des fêtes (reprise)": "La Reine des neiges : Joyeuses fêtes avec Olaf",
  "le bleu lumière (reprise)": "Vaiana",
  "le bossu de notre-dame": "Le Bossu de Notre-Dame",
  "le chant du renne": "La Reine des neiges",
  "le festin": "Ratatouille",
  "le gospel pur i": "Hercule",
  "le gospel pur ii": "Hercule",
  "le gospel pur iii": "Hercule",
  "le monde es mi familia": "Coco",
  "le rapport du matin": "Le Roi lion",
  "les aristochats": "Les Aristochats",
  "les cloches de notre-dame": "Le Bossu de Notre-Dame",
  "les corbeaux": "Dumbo",
  "les grands esprits": "Frère des ours",
  "let it go": "La Reine des neiges",
  "libérée, délivrée": "La Reine des neiges",
  "life is a highway": "Cars",
  "life's incredible again": "Les Indestructibles 2",
  "logo te pate": "Vaiana",
  "mary poppins": "Mary Poppins",
  "mcqueen and sally": "Cars",
  "mulan": "Mulan",
  "ne m'oublie pas (berceuse)": "Coco",
  "ne m'oublie pas (ernesto de la cruz)": "Coco",
  "ne m'oublie pas (retrouvailles)": "Coco",
  "ne parlons pas de bruno": "Encanto",
  "nemo egg (main title)": "Le Monde de Nemo",
  "night falls": "Descendants 3",
  "nobody like u": "Alerte rouge",
  "nous sommes un": "Le Roi lion 2",
  "on my way": "Frère des ours",
  "partir là-bas": "La Petite Sirène",
  "peter pan": "Peter Pan",
  "pinocchio": "Pinocchio",
  "planes": "Planes",
  "planes: fire & rescue": "Planes 2",
  "pocahontas": "Pocahontas",
  "pocahontas - une légende indienne": "Pocahontas",
  "pocahontas, une légende indienne": "Pocahontas",
  "prince ali": "Aladdin",
  "quand je serai plus grand": "La Reine des neiges 2",
  "quand on prie la bonne étoile": "Pinocchio",
  "que sais-je faire d'autre?": "Encanto",
  "queen of mean": "Descendants 3",
  "raiponce": "Raiponce",
  "real gone": "Cars",
  "rebelle": "Rebelle",
  "recognizer": "Tron : L'Héritage",
  "sh-boom": "Cars",
  "siffler en travaillant": "Blanche-Neige et les Sept Nains",
  "sifflez en travaillant (whistle while you work)": "Blanche-Neige et les Sept Nains",
  "sous l'océan": "La Petite Sirène",
  "soyez prêtes": "Le Roi lion",
  "space between": "Descendants 3",
  "steal the show": "Élémentaire",
  "tarzan": "Tarzan",
  "te fiti": "Vaiana",
  "the glory days": "Les Indestructibles",
  "the good dinosaur": "Le Voyage d'Arlo",
  "the grid": "Tron : L'Héritage",
  "the lion king": "Le Roi lion",
  "the muppet movie": "Les Muppets",
  "this is the thanks i get?!": "Wish",
  "thomas o'malley": "Les Aristochats",
  "tout le monde connaît juanita": "Coco",
  "tout le monde veut devenir un cat": "Les Aristochats",
  "toy story": "Toy Story",
  "transformation": "Frère des ours",
  "try everything": "Zootopie",
  "tulou tagaloa": "Vaiana",
  "une étoile est née": "Hercule",
  "up with titles": "Là-haut",
  "virginia compagnie": "Pocahontas",
  "winnie l'ourson": "Winnie l'ourson",
  "you're welcome": "Vaiana",

  // ---------- Jeux vidéo ----------
  "animal crossing: new horizons main theme": "Animal Crossing",
  "antibirth": SKIP,
  "assassins creed": "Assassin's Creed",
  "assassin's creed valhalla: the ravens saga": "Assassin's Creed Valhalla",
  "baldur's gate 3: streets and taverns": "Baldur's Gate 3",
  "becalmed": SKIP,
  "biohazard village": "Resident Evil Village",
  "bird and bear: music from banjo kazooie": "Banjo-Kazooie",
  "blue prince - the": "Blue Prince",
  "brawl stars original menu theme": "Brawl Stars",
  "call of duty: black ops – zombies": "Call of Duty: Black Ops",
  "castlevania stage 1": "Castlevania",
  "champions": SKIP,
  "children of termina": "Zelda : Majora's Mask",
  "city of rome": SKIP,
  "commodoro 64-medley": SKIP,
  "crash bandicoot themes orchestrated": "Crash Bandicoot",
  "crash bandicoot n. sane trilogy": "Crash Bandicoot",
  "crono cross": "Chrono Cross",
  "cyberpunk 2077: radio": "Cyberpunk 2077",
  "demon slayer opening": SKIP,
  "distant worlds ii: more music from final fantasy": "Final Fantasy",
  "dk island swing": "Donkey Kong Country",
  "ducktales": "La Bande à Picsou",
  "elder scrolls": "The Elder Scrolls",
  "fallout 76 - take me home, country roads": "Fallout 76",
  "final fantasy vii advent children": "Final Fantasy VII",
  "fortnite battle royale": "Fortnite",
  "fortnite season 1 & 2 main menu music": "Fortnite",
  "ftl: faster than light -": "FTL: Faster Than Light",
  "genshin impact - forest of jnana and vidya": "Genshin Impact",
  "genshin impact - outside it is growing dark": "Genshin Impact",
  "grand theft auto iv": "GTA IV",
  "grand theft auto vi trailer": "GTA VI",
  "grimm troupe": "Hollow Knight",
  "the grimm troupe": "Hollow Knight",
  "hades ii:": "Hades II",
  "helldivers 2 main theme - \"a cup of liber-tea\"": "Helldivers 2",
  "i'm still standing - space marine": SKIP,
  "ico～霧の中の旋律～": "ICO",
  "lament of orpheus": SKIP,
  "legend of zelda": "The Legend of Zelda",
  "the legend of": "The Legend of Zelda",
  "les aventures de sonic": "Sonic",
  "sonic the hedgehog": "Sonic",
  "little big adventure 2 o.s.t.": "Little Big Adventure 2",
  "little big music extra: more littlebigplanet 2 musical oddities": "LittleBigPlanet 2",
  "lost woods": "The Legend of Zelda",
  "mii channel": "Wii (Chaîne Mii)",
  "nintendo wii": "Wii (Chaîne Mii)",
  "minecraft - volume alpha": "Minecraft",
  "mortal kombat theme": "Mortal Kombat",
  "nessary evil": SKIP,
  "nesessary evil": SKIP,
  "oneshot: solstice": "OneShot",
  "outer wilds: echoes of the eye": "Outer Wilds",
  "outer wilds: echoes of the eye deluxe": "Outer Wilds",
  "outlaws from the west": SKIP,
  "overcooked! - the kingdom tour": "Overcooked!",
  "pacman": "Pac-Man",
  "parry gripp mega-party": SKIP,
  "plants vs zombies": "Plantes contre Zombies",
  "play! opening fanfare": SKIP,
  "poison mind / castlevania": "Castlevania",
  "rainbow road: a tribute to mario kart": "Mario Kart",
  "rayman – 30th anniversary edition": "Rayman",
  "resident evil village": "Resident Evil Village",
  "resident evil: retribution": SKIP,
  "rocket league theme": "Rocket League",
  "shanty selects": SKIP,
  "sly cooper: thieves in time theme": "Sly Cooper",
  "squidography, vol. iv": SKIP,
  "teenage mutant ninja turtles": "Les Tortues Ninja",
  "tetris piano opus no. 1": "Tetris",
  "the best video game music": SKIP,
  "the best video game music volume one": SKIP,
  "the elder scrolls iv": "The Elder Scrolls IV : Oblivion",
  "the elder scrolls v: skyrim": "Skyrim",
  "the sims": "Les Sims",
  "the sims 2": "Les Sims 2",
  "the sims 3": "Les Sims 3",
  "the tale of a cruel world": SKIP,
  "the tomb raider suite": "Tomb Raider",
  "transfiguration": SKIP,
  "trine 2 soundtrack": "Trine 2",
  "war zone": SKIP,
  "warcraft suite": "Warcraft",
  "earthworm jim anthology": "Earthworm Jim",
  "yum yum breakfast burrito": SKIP,
  "モンスターハンターワールド:アイスボーン オリジナル・サウンドトラック": "Monster Hunter World",

  // ---------- Ajouts : nouvelles playlists ----------
  "vaiana 2": "Vaiana 2",
  "brother bear": "Frère des ours",
  "the jungle book": "Le Livre de la jungle",
  "the hunchback of notre dame": "Le Bossu de Notre-Dame",
  "bambi": "Bambi",
  "coco": "Coco",
  "la reine des neiges 2": "La Reine des neiges 2",
  "encanto: la fantastique famille madrigal": "Encanto",
  "wish: asha et la bonne étoile": "Wish : Asha et la bonne étoile",
  "vaiana - la légende du bout du monde": "Vaiana",
  "toy story 5": "Toy Story 5",
  "tendre rêve (de ‘cendrillon’)": "Cendrillon",
  "beauty and the beast": "La Belle et la Bête",
  "hoppers": SKIP,
  "alice's": "Alice au pays des merveilles",
  "another day of sun": "La La Land",
  "arrival to earth": "Transformers",
  "back to the future": "Retour vers le futur",
  "becoming one of \"the people\" becoming one with neytiri": "Avatar",
  "ben": SKIP,
  "boo's going home": "Monstres et Cie",
  "calling you": "Bagdad Café",
  "cancion del mariachi (desperado) [antonio banderas guitar]": "Desperado",
  "canción del mariachi (ilia topuria \"el matador\" anthem)": SKIP,
  "cast away: end title": "Seul au monde",
  "catch me if you can": "Arrête-moi si tu peux",
  "coffey on the mile": "La Ligne verte",
  "don't cry for me argentina": "Evita",
  "e.t. : john williams: e.t.: flying": "E.T. l'extra-terrestre",
  "end credits": SKIP,
  "fever": SKIP,
  "fox fanfare (instrumental)": SKIP,
  "harry potter and the deathly hallows, pt. 2": "Harry Potter",
  "hawaiian roller coaster ride": "Lilo et Stitch",
  "hedwig's": "Harry Potter",
  "hey baby": "Dirty Dancing",
  "hey pachuco!": "The Mask",
  "hogwarts' march": "Harry Potter",
  "i will always love you (film: bodyguard)": "Bodyguard",
  "i'm forrest... forrest gump": "Forrest Gump",
  "in the deathcar": "Arizona Dream",
  "indiana jones and the raiders of the lost ark": "Indiana Jones",
  "introduction (titles)": SKIP,
  "it's finn mcmissile!": "Cars 2",
  "jaws : john williams: jaws: theme from \"jaws\"": "Les Dents de la mer",
  "john williams: the cowboys: overture": SKIP,
  "john williams: the tale of viktor navorski": "Le Terminal",
  "le bon la brute et le truand": "Le Bon, la Brute et le Truand",
  "love is strange": "Dirty Dancing",
  "love theme from \"the godfather\"": "Le Parrain",
  "main title and first victim": "Les Dents de la mer",
  "main titles (charlie and the chocolate factory)": "Charlie et la Chocolaterie",
  "now we are free": "Gladiator",
  "prelude and main title march": "Superman",
  "professor umbridge": "Harry Potter",
  "prologue": SKIP,
  "prologue (<)": SKIP,
  "r. strauss: 2001: a space odyssey": "2001, l'Odyssée de l'espace",
  "saving private ryan": "Il faut sauver le soldat Ryan",
  "schindler's list": "La Liste de Schindler",
  "see you again": "Fast & Furious 7",
  "star wars, episode v \"the empire strikes back\": the imperial march": "Star Wars",
  "the adventures of tintin": "Les Aventures de Tintin",
  "the avengers": "Avengers",
  "the battle": "Gladiator",
  "the hunger games: mockingjay": "Hunger Games",
  "the imperial march": "Star Wars",
  "the lion king orchestra suite": "Le Roi lion",
  "the matrix": "Matrix",
  "the maze runner": "Le Labyrinthe",
  "the minimoys finale": "Arthur et les Minimoys",
  "the polar express": "Le Pôle express",
  "time": "Inception",
  "unchained melody": "Ghost",
  "unchained melody (film: ghost)": "Ghost",
  "i'm always here": "Alerte à Malibu",
  "chi maï": SKIP,
  "clair de lune": SKIP,
  "l'eurovision (te deum)": "L'Eurovision",
  "la queuleuleu (la classe)": "La Classe",
  "les animaux du monde: le lion et le chat": "Les Animaux du monde",
  "arnold et willy (générique vf)": "Arnold et Willy",
  "c’est la vie": SKIP,
  "essaye d'imaginer": SKIP,
  "générique les découvreurs": "Les Découvreurs",
  "je m'appelle hélène": "Hélène et les Garçons",
  "la kiffance": SKIP,
  "li tourner 2013": SKIP,
  "o landi nga ti awa": SKIP,
  "one more time": SKIP,
  "oliver": SKIP,
  "pour l'amour d'un garçon": "Hélène et les Garçons",
  "poussez-vous les moches !": SKIP,
  "send me an angel": SKIP,
  "tremblement de terre": SKIP,
  "un amour de vacances": SKIP,
  "wingman": SKIP,
  "rouli rouli roulette": SKIP,
  "the muppet show": "Le Muppet Show",
  "dis moi bioman": "Bioman",
  "bisous, bisous, gentils bisounours": "Les Bisounours",
  "bisous bisous gentil bisounours": "Les Bisounours",
  "dors mon petit poney": "Mon petit poney",
  "la chanson de babar": "Babar",
  "la chanson de casimir": "L'Île aux enfants",
  "la chanson de nono": "Ulysse 31",
  "c'est moi qui suis colargol": "Colargol",
  "les 4 filles du dr march": "Les Quatre Filles du docteur March",
  "un collège fou fou": "Un collège fou fou fou",
  "deux flics a miami": "Deux flics à Miami",
  "drôles de dames": "Drôles de dames",
  "mac gyver": "MacGyver",
  "woody wood pecker": "Woody Woodpecker",
  "all for one": SKIP,
  "amigas cheetahs": SKIP,
  "bang bang lucky luke": "Lucky Luke",
  "bet on it": SKIP,
  "big time rush": SKIP,
  "butterfly fly away": SKIP,
  "dexter's laboratory": "Le Laboratoire de Dexter",
  "don't walk away": SKIP,
  "duck tales": "La Bande à Picsou",
  "everything is not as it seems": "Les Sorciers de Waverly Place",
  "fabulous": SKIP,
  "fairly odd parents": "Mes parrains sont magiques",
  "guardians of the galaxy parody": SKIP,
  "humuhumunukunukuapua'a": SKIP,
  "hoedown throwdown": SKIP,
  "i don't dance": SKIP,
  "introducing me": SKIP,
  "leave it all to me": "iCarly",
  "lemonade mouth": SKIP,
  "make it shine": "Victorious",
  "simpsons": "Les Simpson",
  "something to dance for": SKIP,
  "southpark": "South Park",
  "spiderman l'araignée": "Spider-Man",
  "spongebob squarepants theme song": "Bob l'éponge",
  "ttylxox": SKIP,
  "teletubbies": "Les Teletubbies",
  "the best of both worlds": "Hannah Montana",
  "the climb": SKIP,
  "the party's just begun": SKIP,
  "turn up the music": SKIP,
  "we are w.i.t.c.h": "W.I.T.C.H.",
  "who said": "Hannah Montana",
  "work this out": SKIP,
  "you are the music in me": SKIP,
  "yu-gi-oh": "Yu-Gi-Oh!",
  "bob-omb battlefield": "Super Mario 64",
  "bob-omb battlefield from super mario 64": "Super Mario 64",
  "bossa de link": "The Legend of Zelda",
  "castle": SKIP,
  "delfino plaza": "Super Mario Sunshine",
  "isle delfino": "Super Mario Sunshine",
  "entertainment system 64": SKIP,
  "super entertainment system": SKIP,
  "no nes for the wicked": SKIP,
  "retro remix revue": SKIP,
  "green hill zone": "Sonic",
  "koopa beach": "Mario Kart",
  "legend of zelda – the windwaker": "Zelda : The Wind Waker",
  "majora's mask orchestrated": "Zelda : Majora's Mask",
  "ocarina of time": "Zelda : Ocarina of Time",
  "the legend of zelda - ocarina of time": "Zelda : Ocarina of Time",
  "zelda: link's ocarina orchestrated": "Zelda : Ocarina of Time",
  "skyward sword": "Zelda : Skyward Sword",
  "super mario kart album": "Mario Kart",
  "the legend of zelda - best soundtracks": "The Legend of Zelda",
  "a link to the past": "Zelda : A Link to the Past"
};

const keyOf = label => String(label).normalize("NFC").toLowerCase().replace(/[’‘]/g, "'").replace(/\s+/g, " ").trim();

// Nom français d'une réponse : string, null (morceau à écarter) ou undefined (inconnue).
export function frName(label) {
  const key = keyOf(label);
  return Object.prototype.hasOwnProperty.call(FR_NAMES, key) ? FR_NAMES[key] : undefined;
}
