// Textes de Survivor : défis physiques (par mode de soirée) et punitions (par niveau d'alcool).
// Repris tels quels de l'ancienne version.

export const PHYSICAL_CHALLENGES = {
  Chill: [
    "Équilibre : tenir le plus longtemps sur un pied",
    "Équilibre : tenir sur un pied les yeux fermés",
    "Adresse : lancer une pièce dans un verre en 3 essais (le plus de réussites gagne)",
    "Adresse : faire tenir une cuillère sur son nez le plus longtemps",
    "Mémoire : retenir 8 objets montrés 10 secondes, puis les citer",
    "Mémoire : répéter une suite de chiffres de plus en plus longue",
    "Rapidité : dire l’alphabet à l’envers le plus vite",
    "Rapidité : citer 10 pays le plus vite possible",
    "Concentration : ne pas cligner des yeux le plus longtemps",
    "Sang-froid : rester sans rire pendant que le groupe essaie de te faire craquer",
    "Statue : ne pas bouger d’un millimètre, le premier qui bouge perd",
    "Chifoumi en tournoi : le vainqueur final gagne",
    "Tirage au doigt : pouce contre pouce en élimination directe",
    "Observation : trouver un objet bleu, le dernier à le montrer perd",
    "Dessin : dessiner un chat les yeux fermés, le groupe vote",
    "Mime : faire deviner un animal le plus vite",
    "Devinette : le premier qui trouve gagne, le dernier à répondre perd",
    "Empilement : empiler le plus d’objets en 30 secondes sans que ça tombe",
    "Souffle : tenir une note de musique le plus longtemps",
    "Patience : garder une pièce en équilibre sur le dos de la main le plus longtemps",
    "Rapidité : écrire son prénom avec la main faible, le plus lisible gagne",
    "Mémoire : réciter les prénoms de tout le groupe dans l’ordre des places",
    "Chaise musicale sans chaise : le dernier assis par terre perd",
    "Adresse : faire rouler une bouteille vide jusqu’à un point précis",
    "Concentration : compter jusqu’à 30 en sautant les multiples de 3, le premier qui se trompe perd",
    "Pile ou face en série : celui qui devine le plus de fois gagne",
    "Rapidité : faire 10 claquements de doigts le plus vite",
    "Équilibre : marcher sur une ligne imaginaire en avant puis en arrière",
    "Grimace : la plus moche gagne, la moins drôle perd (vote du groupe)",
    "Chant : chanter le plus aigu possible, le groupe vote",
    "Dernier à toucher le sol",
    "Dernier à lever les deux mains",
    "Dernier à toucher un mur",
    "Dernier à faire un cœur avec les mains",
    "Dernier à montrer un objet rouge",
    "Dernier à faire semblant de dormir",
    "Dernier à pointer le plafond",
    "Dernier à faire un clin d’œil",
    "Dernier à toucher son nez",
    "Dernier à faire un signe de paix",
  ],
  Party: [
    "Danse : le meilleur pas de danse gagne, le pire perd (vote du groupe)",
    "Karaoké express : chanter le refrain d’un tube, le groupe vote",
    "Rapidité : le premier à faire tenir un bouchon debout gagne",
    "Adresse : lancer une balle de papier dans une poubelle à 3 mètres",
    "Équilibre : poser un verre en plastique sur sa tête et marcher jusqu’au mur",
    "Limbo : passer sous un balai de plus en plus bas",
    "Mémoire : retenir l’ordre de 6 verres ou objets, puis les remettre en place",
    "Rapidité : nommer 5 chansons d’un même artiste",
    "Blind test humain : fredonner un tube, le premier qui trouve gagne",
    "Sang-froid : garder son sérieux pendant que quelqu’un fait un discours ridicule",
    "Statue de danse : figé dès que la musique s’arrête, le premier qui bouge perd",
    "Duel de regard en tournoi : le premier qui rit ou cligne perd",
    "Tir de précision : faire glisser une pièce sur la table au plus près du bord sans tomber",
    "Course en crabe jusqu’au mur et retour",
    "Rapidité : faire le tour de la table en sautant à cloche-pied",
    "Mime : faire deviner un film, le plus rapide gagne",
    "Chorégraphie : reproduire 4 pas inventés par l’hôte, le moins fidèle perd",
    "Air guitar : la meilleure prestation gagne (vote)",
    "Imitation : la meilleure imitation de célébrité gagne (vote)",
    "Mémoire musicale : finir les paroles d’un tube lancé par l’hôte",
    "Rapidité : être le premier à trouver 3 objets de couleurs différentes",
    "Concours de beatbox : le groupe vote",
    "Concours de rire le plus contagieux",
    "Défi du DJ : le premier à reconnaître la chanson qui passe gagne",
    "Ola parfaite : celui qui la rate perd",
    "Défi bras tendus : tenir une bouteille pleine à bout de bras le plus longtemps",
    "Concours de clin d’œil le plus séducteur (vote)",
    "Adresse : faire tomber une pièce dans un verre en la faisant rebondir sur la table",
    "Rapidité : citer 5 cocktails en 10 secondes",
    "Concours du meilleur toast improvisé (vote)",
    "Dernier à crier « PARTYHUB »",
    "Dernier à lever son verre",
    "Dernier à faire un toast",
    "Dernier à faire un pas de danse",
    "Dernier à taper trois fois sur la table",
    "Dernier à lever les deux pouces",
    "Dernier à dire le nom d’un cocktail",
    "Dernier à faire un dab",
    "Dernier à toucher une bouteille",
    "Dernier à se lever et se rasseoir",
  ],
  Chaos: [
    "Sang-froid : regarder le groupe dans les yeux sans rire pendant 20 secondes",
    "Mensonge : raconter une anecdote vraie ou fausse, celui qui trompe le plus de monde gagne",
    "Interrogatoire : répondre à 5 questions sans dire oui ni non",
    "Statue chaos : rester figé pendant que le groupe essaie de te faire bouger (sans te toucher)",
    "Accusation : désigner le traître du groupe en 5 secondes, le moins convaincant perd",
    "Équilibre : tenir sur un pied en chantant",
    "Mémoire : retenir ce que chaque joueur porte, puis répondre les yeux fermés",
    "Rapidité : être le premier à toucher 4 murs différents",
    "Course lente : le dernier à arriver au mur gagne (sans jamais s’arrêter)",
    "Débat express : défendre l’indéfendable 20 secondes, le groupe vote",
    "Concours de la pire excuse : le groupe vote",
    "Concours du regard le plus dramatique (vote)",
    "Chaise vide : le premier à trouver une place libre après le signal gagne",
    "Rapidité : citer 3 secrets inventés sur toi-même en 10 secondes",
    "Plaidoirie : convaincre le groupe de te donner l’immunité en 15 secondes",
    "Concours du meilleur cri de victoire (vote)",
    "Chuchotement : faire passer une phrase en téléphone arabe, celui qui la déforme le plus perd",
    "Mime d’émotion : faire deviner une émotion, le plus lent à être deviné perd",
    "Pierre-feuille-ciseaux en équipe de deux : l’équipe perdante désigne son perdant",
    "Concentration : réciter une phrase difficile à prononcer 3 fois de suite",
    "Stoïque : garder une main sur la tête et l’autre sur le ventre en tournant",
    "Mémoire : retenir l’ordre de passage de tout le groupe",
    "Réflexe : attraper un objet lâché par l’hôte sans prévenir",
    "Cache-cache express : le dernier trouvé gagne (30 secondes)",
    "Imitation de l’hôte : la meilleure gagne (vote)",
    "Négociation : convaincre quelqu’un d’échanger sa place avec toi",
    "Énigme : le premier qui résout la devinette de l’hôte gagne",
    "Concours du plus long « aaaah » sans reprendre son souffle",
    "Défi aveugle : retrouver sa place les yeux fermés",
    "Concours de la pire confession inventée (vote)",
    "Dernier à crier « JE SUIS SAFE »",
    "Dernier à changer de place",
    "Dernier à pointer la personne la plus suspecte",
    "Dernier à faire un regard dramatique",
    "Dernier à se cacher le visage",
    "Dernier à toucher deux objets différents",
    "Dernier à faire le silence complet",
    "Dernier à faire semblant de pleurer",
    "Dernier à accuser quelqu’un",
    "Dernier à trouver un objet noir",
  ],
  Hardcore: [
    "Endurance : la planche le plus longtemps",
    "Endurance : la chaise contre le mur le plus longtemps",
    "Endurance : bras tendus à l’horizontale le plus longtemps",
    "Force : le plus de pompes en 30 secondes",
    "Force : le plus de squats en 30 secondes",
    "Équilibre : tenir sur un pied, yeux fermés, bras croisés",
    "Vitesse : toucher les 4 coins de la pièce le plus vite",
    "Bras de fer en tournoi : le vainqueur final gagne",
    "Agilité : ramasser 5 objets posés au sol le plus vite",
    "Sang-froid : garder son sérieux pendant que le groupe te fait des compliments",
    "Mémoire : retenir une suite de 10 objets",
    "Rapidité : citer 10 marques de voiture en 15 secondes",
    "Gainage latéral le plus long (chaque côté compte)",
    "Jumping jacks : le plus en 30 secondes",
    "Équilibre : faire 3 tours sur soi-même puis marcher droit",
    "Endurance : tenir une bouteille pleine à bout de bras",
    "Course en sac (ou en sautant pieds joints) jusqu’au mur",
    "Pompes sur les genoux : le plus en 20 secondes",
    "Réflexe : attraper une pièce lancée en l’air, le plus de réussites gagne",
    "Duel de regard + grimaces du groupe : le dernier sérieux gagne",
    "Le mur du silence : ne pas parler pendant 1 minute pendant que le groupe te provoque",
    "Mémoire : réciter les prénoms et les boissons de chacun",
    "Rapidité : le premier à enlever et remettre ses chaussures",
    "Danse de survie : danser 30 secondes non-stop, le moins énergique perd",
    "Cri de guerre : le plus puissant gagne (vote)",
    "Dernier debout : tout le monde s’accroupit, le dernier à craquer gagne",
    "Agilité : se relever du sol sans les mains",
    "Concours de la pose de statue grecque la plus longue",
    "Rapidité : nommer un pays par lettre de A à J",
    "Rapidité : citer 10 capitales en 20 secondes",
    "Dernier à toucher deux murs différents",
    "Dernier à faire 3 tours sur lui-même",
    "Dernier à faire un squat",
    "Dernier à crier « SURVIVOR »",
    "Dernier à toucher une chaussure",
    "Dernier à faire un cri de guerre",
    "Dernier à faire une révérence",
    "Dernier à toucher la table puis le mur",
    "Dernier à se mettre debout",
    "Dernier à faire une pose de bodybuilder",
  ],
};
