// Questions de Most Likely (par mode de soirée) et punitions (par niveau d'alcool).
// Reprises de l'ancienne version.

export const QUESTIONS = {
  Chill: [
    "Qui est le plus susceptible de finir la soirée à parler philo dans un coin ?",
    "Qui est le plus susceptible d’oublier son téléphone partout ?",
    "Qui est le plus susceptible de ramener un animal errant ?",
    "Qui est le plus susceptible de commander à manger pour tout le monde à 3h ?",
    "Qui est le plus susceptible de tomber amoureux en une soirée ?",
    "Qui est le plus susceptible de danser comme si personne ne regardait ?",
    "Qui est le plus susceptible de citer des memes obsolètes ?",
    "Qui est le plus susceptible de s’endormir avant minuit ?",
    "Qui est le plus susceptible de prendre 300 photos floues ?",
    "Qui est le plus susceptible de toujours avoir des snacks sur lui ?",
    "Qui est le plus susceptible de proposer un jeu de société random ?",
    "Qui est le plus susceptible de faire des playlists interminables ?",
    "Qui est le plus susceptible de connaître toutes les paroles de chansons nulles ?",
    "Qui est le plus susceptible de garder un secret pendant 10 ans ?",
    "Qui est le plus susceptible de collectionner des trucs inutiles ?",
    "Qui est le plus susceptible de pleurer devant des vidéos de chiots ?",
    "Qui est le plus susceptible de rester sobre toute la soirée ?",
    "Qui est le plus susceptible de faire des compliments chelous ?",
    "Qui est le plus susceptible de ranger l’appart à 6h du matin ?",
    "Qui est le plus susceptible d’adopter des plantes et de les tuer ?",
    "Qui est le plus susceptible de parler tout seul ?",
    "Qui est le plus susceptible de croire aux signes de l’univers ?",
    "Qui est le plus susceptible de raconter ses rêves bizarres ?",
    "Qui est le plus susceptible d’être toujours en retard ?",
    "Qui est le plus susceptible de chanter sous la douche ?",
    "Qui est le plus susceptible de faire des listes pour tout ?",
    "Qui est le plus susceptible d’avoir peur des araignées ?",
    "Qui est le plus susceptible de finir ses phrases par des emojis ?",
    "Qui est le plus susceptible de collectionner les hoodies ?",
    "Qui est le plus susceptible de regarder des mukbangs pour s’endormir ?",
    "Qui est le plus susceptible de dire ‘c’est pas ce que je voulais dire’ ?",
    "Qui est le plus susceptible d’aimer les dramas des autres ?",
    "Qui est le plus susceptible de faire du journaling ?",
    "Qui est le plus susceptible de parler à ses plantes ?",
    "Qui est le plus susceptible d’avoir 50 onglets ouverts en permanence ?",
    "Qui est le plus susceptible de sauver des animaux sur Internet ?",
    "Qui est le plus susceptible de faire des siestes de 4h ?",
    "Qui est le plus susceptible d’être addict aux réseaux sociaux ?",
    "Qui est le plus susceptible de rire tout seul devant un meme ?",
    "Qui est le plus susceptible de garder tous ses tickets ?",
    "Qui est le plus susceptible de devenir pote avec le serveur ?",
    "Qui est le plus susceptible de faire des blagues nulles ?",
    "Qui est le plus susceptible d’avoir une peluche secrète ?",
    "Qui est le plus susceptible de chanter sous la pluie ?",
    "Qui est le plus susceptible d’oublier de manger ?",
    "Qui est le plus susceptible de faire des câlins à tout le monde ?",
    "Qui est le plus susceptible d’avoir une routine skincare interminable ?",
    "Qui est le plus susceptible de dire ‘je suis fatigué’ toute la soirée ?",
    "Qui est le plus susceptible de faire des grimaces sur les photos ?",
    "Qui est le plus susceptible d’être obsédé par le rangement ?",
    "Qui est le plus susceptible de poser des questions existentielles ?",
    "Qui est le plus susceptible d’avoir une playlist sad ?",
    "Qui est le plus susceptible de collectionner les mugs ?",
    "Qui est le plus susceptible de faire des voix aux animaux ?",
    "Qui est le plus susceptible d’être toujours en train de grignoter ?",
    "Qui est le plus susceptible de prendre des notes sur tout ?",
    "Qui est le plus susceptible de faire des blagues dad ?",
    "Qui est le plus susceptible d’aimer les films d’horreur tout en ayant peur ?",
    "Qui est le plus susceptible de parler en citations ?",
    "Qui est le plus susceptible d’avoir une opinion sur tout ?",
    "Qui est le plus susceptible de faire des DIY ratés ?",
    "Qui est le plus susceptible de devenir pote avec les grands-parents ?",
    "Qui est le plus susceptible de chanter en voiture ?",
    "Qui est le plus susceptible d’avoir une addiction au café ?",
    "Qui est le plus susceptible de faire des tier lists ?",
    "Qui est le plus susceptible de garder ses ex en ami ?",
    "Qui est le plus susceptible de dire ‘je vais me coucher tôt’ et finir à 5h ?",
    "Qui est le plus susceptible d’être toujours en jogging ?",
    "Qui est le plus susceptible de faire des mimes en racontant une histoire ?",
    "Qui est le plus susceptible d’avoir une chambre bordélique ?",
    "Qui est le plus susceptible de poser des questions philo quand il est bourré ?",
    "Qui est le plus susceptible d’aimer les câlins ?",
    "Qui est le plus susceptible de faire des recherches Wikipédia à 4h du mat ?",
    "Qui est le plus susceptible de collectionner les stickers ?",
    "Qui est le plus susceptible de dire ‘je suis trop vieux’ puis de le faire quand même ?",
    "Qui est le plus susceptible d’avoir un crush sur une voix ?",
    "Qui est le plus susceptible de faire des appels vidéo interminables ?",
    "Qui est le plus susceptible de rater ses recettes healthy ?",
    "Qui est le plus susceptible de parler à ses posters ?",
    "Qui est le plus susceptible d’avoir peur du vide ?",
    "Qui est le plus susceptible de faire des sons en mangeant ?",
    "Qui est le plus susceptible de garder ses souvenirs d’enfance ?",
    "Qui est le plus susceptible de dire oui à tout puis regretter ?",
    "Qui est le plus susceptible d’être le roi des memes ?",
    "Qui est le plus susceptible de faire des danses TikTok ratées ?",
    "Qui est le plus susceptible d’avoir des chaussettes dépareillées ?",
    "Qui est le plus susceptible de blaguer sur son malheur ?",
    "Qui est le plus susceptible de devenir émotif avec la musique ?",
    "Qui est le plus susceptible d’avoir 10 projets inachevés ?",
    "Qui est le plus susceptible de faire des compliments random ?",
    "Qui est le plus susceptible d’être toujours en retard avec une excuse bidon ?",
    "Qui est le plus susceptible de faire des jeux de mots pourris ?",
    "Qui est le plus susceptible d’avoir une peur irrationnelle ?",
    "Qui est le plus susceptible de parler en dormant ?",
    "Qui est le plus susceptible d’être le plus gentil du groupe ?",
    "Qui est le plus susceptible de faire des selfies avec des inconnus ?",
    "Qui est le plus susceptible d’aimer les soirées calmes ?",
    "Qui est le plus susceptible de garder une lettre d’amour ?",
    "Qui est le plus susceptible de googler ses symptômes ?",
    "Qui est le plus susceptible de dire ‘juste un épisode’ et binge-watcher toute la saison ?",
    "Qui est le plus susceptible d’être toujours positif ?",
    "Qui est le plus susceptible de faire des voix en vocal ?",
    "Qui est le plus susceptible d’être addict aux stories ?",
    "Qui est le plus susceptible de faire des listes sans jamais rien faire ?",
    "Qui est le plus susceptible de devenir pote avec tout le monde ?",
    "Qui est le plus susceptible d’avoir un carnet de pensées ?",
    "Qui est le plus susceptible de blaguer sur son ex ?",
    "Qui est le plus susceptible de danser seul dans sa chambre ?",
    "Qui est le plus susceptible d’être le thérapeute du groupe ?",
    "Qui est le plus susceptible de collectionner les mugs mignons ?",
    "Qui est le plus susceptible de dire ‘je change’ tous les mois ?",
    "Qui est le plus susceptible d’avoir une playlist pour chaque mood ?",
    "Qui est le plus susceptible de faire des câlins longs ?",
    "Qui est le plus susceptible de parler de rêves lucides ?",
    "Qui est le plus susceptible de grignoter healthy puis junk food juste après ?",
    "Qui est le plus susceptible de faire des tier lists de ses potes ?",
    "Qui est le plus susceptible de garder ses bracelets brésiliens ?",
    "Qui est le plus susceptible de faire des blagues nulles pour détendre l’ambiance ?",
    "Qui est le plus susceptible d’avoir peur des clowns ?",
    "Qui est le plus susceptible de dire ‘je t’aime’ bourré à ses potes ?",
    "Qui est le plus susceptible de collectionner les Polaroid ?",
    "Qui est le plus susceptible de tenir ses résolutions seulement 3 jours ?",
    "Qui est le plus susceptible de faire des voix bizarres au téléphone ?",
    "Qui est le plus susceptible de collectionner les figurines ?",
    "Qui est le plus susceptible d’être toujours en train de dessiner ?",
    "Qui est le plus susceptible de faire des blagues sur son signe astro ?",
    "Qui est le plus susceptible d’avoir peur des hauteurs ?"
  ],

  Party: [
    "Qui est le plus susceptible de finir sur la table à danser ?",
    "Qui est le plus susceptible de lancer une tournée générale sans avoir l’argent ?",
    "Qui est le plus susceptible d’inviter tout le monde à l’after ?",
    "Qui est le plus susceptible de perdre ses clés en 20 minutes ?",
    "Qui est le plus susceptible de se mettre torse nu ?",
    "Qui est le plus susceptible de chanter dans la rue ?",
    "Qui est le plus susceptible de draguer le barman / la barmaid ?",
    "Qui est le plus susceptible de faire un twerk raté ?",
    "Qui est le plus susceptible d’organiser un jeu à boire ?",
    "Qui est le plus susceptible de finir avec le maquillage détruit ?",
    "Qui est le plus susceptible de voler une bouteille ?",
    "Qui est le plus susceptible de faire un body shot ?",
    "Qui est le plus susceptible de danser sur le bar ?",
    "Qui est le plus susceptible de ramener un inconnu ?",
    "Qui est le plus susceptible de mixer tous les alcools ?",
    "Qui est le plus susceptible de faire un striptease raté ?",
    "Qui est le plus susceptible de perdre une chaussure ?",
    "Qui est le plus susceptible de crier ‘j’aime tout le monde’ ?",
    "Qui est le plus susceptible de faire un karaoké dramatique ?",
    "Qui est le plus susceptible de finir en string ?",
    "Qui est le plus susceptible de vomir puis continuer à boire ?",
    "Qui est le plus susceptible de prendre des photos complètement bourré ?",
    "Qui est le plus susceptible de french kiss un pote ?",
    "Qui est le plus susceptible de danser collé ?",
    "Qui est le plus susceptible de perdre son portefeuille ?",
    "Qui est le plus susceptible de faire un shot dans le nombril ?",
    "Qui est le plus susceptible d’inviter des randoms ?",
    "Qui est le plus susceptible de finir à poil dans une piscine ?",
    "Qui est le plus susceptible de crier des confessions ?",
    "Qui est le plus susceptible de faire un pari cul ?",
    "Qui est le plus susceptible de faire un conga line ?",
    "Qui est le plus susceptible de se faire tatouer temporaire ?",
    "Qui est le plus susceptible de draguer en groupe ?",
    "Qui est le plus susceptible de finir sur les épaules de quelqu’un ?",
    "Qui est le plus susceptible de faire un moonwalk raté ?",
    "Qui est le plus susceptible de voler un panneau de signalisation ?",
    "Qui est le plus susceptible de chanter du rap en playback ?",
    "Qui est le plus susceptible de faire un dab à chaque fois ?",
    "Qui est le plus susceptible de ramener 5 inconnus ?",
    "Qui est le plus susceptible de faire un battle de danse ?",
    "Qui est le plus susceptible de finir avec des bisous partout ?",
    "Qui est le plus susceptible de voler des verres ?",
    "Qui est le plus susceptible de faire un toast à n’importe quoi ?",
    "Qui est le plus susceptible de faire un flip cup ?",
    "Qui est le plus susceptible de danser sur la table basse ?",
    "Qui est le plus susceptible de faire un beer pong catastrophique ?",
    "Qui est le plus susceptible de perdre ses affaires partout ?",
    "Qui est le plus susceptible de faire un selfie de groupe toutes les 10 minutes ?",
    "Qui est le plus susceptible de faire un mur de shots ?",
    "Qui est le plus susceptible de danser avec un inconnu toute la soirée ?",
    "Qui est le plus susceptible de faire un Never Have I Ever sauvage ?",
    "Qui est le plus susceptible de finir la bouteille de vodka ?",
    "Qui est le plus susceptible de crier ‘shots shots shots’ ?",
    "Qui est le plus susceptible de danser sur du reggaeton ?",
    "Qui est le plus susceptible de finir avec du maquillage sur le visage ?",
    "Qui est le plus susceptible de faire un challenge TikTok bourré ?",
    "Qui est le plus susceptible de perdre son Uber ?",
    "Qui est le plus susceptible de mixer Red Bull avec tout ce qui passe ?",
    "Qui est le plus susceptible de finir la soirée à danser sous la pluie ?",
    "Qui est le plus susceptible de faire un shot gun ?",
    "Qui est le plus susceptible de danser en chaussettes ?",
    "Qui est le plus susceptible de ramener tout le groupe à l’after ?",
    "Qui est le plus susceptible de faire un karaoké seul sur scène ?",
    "Qui est le plus susceptible de finir torse nu sur une story ?"
  ],

  Chaos: [
    "Qui est le plus susceptible de déclencher une dispute pour rien ?",
    "Qui est le plus susceptible de fouiller tous les placards de l’appart ?",
    "Qui est le plus susceptible d’appeler son ex à 4h du mat ?",
    "Qui est le plus susceptible de casser un truc cher ?",
    "Qui est le plus susceptible de se perdre en rentrant ?",
    "Qui est le plus susceptible de lancer un pari complètement absurde ?",
    "Qui est le plus susceptible de filmer toute la soirée en story ?",
    "Qui est le plus susceptible de saouler tout le monde ?",
    "Qui est le plus susceptible de commencer un débat que personne ne peut arrêter ?",
    "Qui est le plus susceptible de vomir partout ?",
    "Qui est le plus susceptible de réveiller tout l’immeuble ?",
    "Qui est le plus susceptible de faire un tatouage impulsif ?",
    "Qui est le plus susceptible de dormir dans la rue ?",
    "Qui est le plus susceptible de poster des stories gênantes ?",
    "Qui est le plus susceptible de casser son téléphone ?",
    "Qui est le plus susceptible de se battre avec un pote ?",
    "Qui est le plus susceptible de partir du resto en oubliant de payer (pour de vrai) ?",
    "Qui est le plus susceptible de déclencher un drama ?",
    "Qui est le plus susceptible de faire un mosh pit ?",
    "Qui est le plus susceptible de sauter tout habillé dans une piscine ?",
    "Qui est le plus susceptible d’allumer un barbecue sous la pluie ?",
    "Qui est le plus susceptible de détruire un meuble ?",
    "Qui est le plus susceptible de courir nu ?",
    "Qui est le plus susceptible de grimper sur le toit d’une voiture pour une photo ?",
    "Qui est le plus susceptible de repartir d’un magasin avec un panier qu’il ne voulait pas ?",
    "Qui est le plus susceptible de faire une blague qui va trop loin ?",
    "Qui est le plus susceptible de déclencher les pompiers ?",
    "Qui est le plus susceptible de se faire un meilleur ami inconnu en 10 minutes ?",
    "Qui est le plus susceptible de poster une vidéo compromettante ?",
    "Qui est le plus susceptible de disparaître de la soirée sans prévenir ?",
    "Qui est le plus susceptible de crier sur tout le monde ?",
    "Qui est le plus susceptible de faire un pari qui finit aux urgences ?",
    "Qui est le plus susceptible de détruire la playlist ?",
    "Qui est le plus susceptible de faire un trou dans le mur ?",
    "Qui est le plus susceptible de se faire refouler à l’entrée d’une boîte ?",
    "Qui est le plus susceptible de faire un live TikTok chaotique ?",
    "Qui est le plus susceptible de se disputer avec le DJ ?",
    "Qui est le plus susceptible de se faire jeter dehors ?",
    "Qui est le plus susceptible de hurler des secrets ?",
    "Qui est le plus susceptible de déclencher un drama familial ?",
    "Qui est le plus susceptible de faire une guerre de nourriture ?",
    "Qui est le plus susceptible de casser la porte des toilettes ?",
    "Qui est le plus susceptible de hurler son amour à 5h du matin ?",
    "Qui est le plus susceptible de déclencher une alarme ?",
    "Qui est le plus susceptible de faire un prank qui finit mal ?"
  ],

  Hardcore: [
    "Qui est le plus susceptible d’avoir une double vie sexuelle ?",
    "Qui est le plus susceptible de ghoster après avoir fait des trucs dégueulasses ?",
    "Qui est le plus susceptible d’avoir un compte OnlyFans secret ?",
    "Qui est le plus susceptible de mentir sur son body count depuis des années ?",
    "Qui est le plus susceptible d’avoir trahi tous ses potes pour du sexe ?",
    "Qui est le plus susceptible d’avoir couché avec son ex en étant en couple ?",
    "Qui est le plus susceptible de fantasmer sur des trucs vraiment tabous ?",
    "Qui est le plus susceptible d’avoir un crush sur quelqu’un ici tout en le détestant ?",
    "Qui est le plus susceptible d’avoir couché avec le partenaire de son meilleur ami ?",
    "Qui est le plus susceptible d’avoir déjà participé à une orgie ?",
    "Qui est le plus susceptible d’avoir un historique de recherche porno terrifiant ?",
    "Qui est le plus susceptible d’avoir un deuxième téléphone pour ses plans ?",
    "Qui est le plus susceptible de finir bourré en premier ?",
    "Qui est le plus susceptible de vomir le plus tôt dans la soirée ?",
    "Qui est le plus susceptible de se mettre torse nu après 4 verres ?",
    "Qui est le plus susceptible de draguer tout le monde quand il est saoul ?",
    "Qui est le plus susceptible de pleurer bourré ?",
    "Qui est le plus susceptible de dire des secrets qu’il regrettera ?",
    "Qui est le plus susceptible de finir à poil ?",
    "Qui est le plus susceptible de devenir hyper affectueux après l’alcool ?",
    "Qui est le plus susceptible de faire des déclarations d’amour cheloues ?",
    "Qui est le plus susceptible de dire ‘je vous aime tous’ ?",
    "Qui est le plus susceptible de faire des paris stupides ?",
    "Qui est le plus susceptible de regretter toute sa vie le lendemain ?",
    "Qui est le plus susceptible de se disputer avec ses meilleurs potes ?",
    "Qui est le plus susceptible de draguer son ex bourré ?",
    "Qui est le plus susceptible de se réveiller sans aucun souvenir ?",
    "Qui est le plus susceptible d’avoir un plan cul dans son répertoire en ce moment ?",
    "Qui est le plus susceptible d’avoir déjà embrassé deux personnes dans la même soirée ?",
    "Qui est le plus susceptible d’avoir déjà couché le premier soir ?",
    "Qui est le plus susceptible d’avoir déjà envoyé un nude à la mauvaise personne ?",
    "Qui est le plus susceptible d’avoir déjà fait l’amour dans un endroit insolite ?",
    "Qui est le plus susceptible de tenir une liste de ses conquêtes ?",
    "Qui est le plus susceptible d’avoir déjà simulé ?",
    "Qui est le plus susceptible de se remettre avec son ex au moins trois fois ?",
    "Qui est le plus susceptible d’avoir eu un crush sur le ou la partenaire d’un pote ?",
    "Qui est le plus susceptible d’avoir déjà fait un plan à trois ?",
    "Qui est le plus susceptible de draguer sur trois applis de rencontre en même temps ?",
    "Qui est le plus susceptible d’avoir dragué quelqu’un uniquement pour rendre son ex jaloux ?",
    "Qui est le plus susceptible d’avoir déjà embrassé quelqu’un de cette pièce ?",
    "Qui est le plus susceptible d’avoir menti sur son âge pour séduire ?",
    "Qui est le plus susceptible de se considérer comme le meilleur coup de la pièce ?",
    "Qui est le plus susceptible d’avoir des menottes chez lui ?",
    "Qui est le plus susceptible de s’être déjà fait surprendre en pleine action ?",
    "Qui est le plus susceptible d’avoir déjà fait un strip-tease pour quelqu’un ?",
    "Qui est le plus susceptible de tomber amoureux de son plan cul ?",
    "Qui est le plus susceptible d’avoir déjà réveillé ses voisins… et pas en ronflant ?",
    "Qui est le plus susceptible de stalker le nouveau ou la nouvelle de son ex ?",
    "Qui est le plus susceptible de garder des photos de son ex dans un dossier caché ?",
    "Qui est le plus susceptible d’avoir oublié le prénom de quelqu’un le lendemain matin ?",
    "Qui est le plus susceptible d’avoir déjà fait un walk of shame ?",
    "Qui est le plus susceptible de flirter avec quelqu’un qui est en couple ?",
    "Qui est le plus susceptible d’avoir déjà eu deux dates le même jour ?",
    "Qui est le plus susceptible d’avoir un jouet bien caché dans sa table de nuit ?",
    "Qui est le plus susceptible d’avoir fait du sexting pendant un repas de famille ?",
    "Qui est le plus susceptible d’envoyer « tu dors ? » à 3h du matin ?",
    "Qui est le plus susceptible d’avoir embrassé quelqu’un juste pour gagner un pari ?",
    "Qui est le plus susceptible d’avoir déjà dragué un prof ou un boss ?",
    "Qui est le plus susceptible d’avoir craqué pour le ou la meilleure amie de son ex ?",
    "Qui est le plus susceptible d’avoir déjà eu une relation cachée ?",
    "Qui est le plus susceptible de finir la soirée chez quelqu’un rencontré il y a 2 heures ?",
    "Qui est le plus susceptible d’avoir menti sur son body count… à la baisse ?",
    "Qui est le plus susceptible d’avoir menti sur son body count… à la hausse ?",
    "Qui est le plus susceptible d’avoir eu un date catastrophique qui a quand même fini au lit ?",
    "Qui est le plus susceptible d’avoir eu une histoire avec un collègue ?",
    "Qui est le plus susceptible d’avoir embrassé quelqu’un du même sexe « pour voir » ?",
    "Qui est le plus susceptible d’avoir dit « c’est la dernière fois » à son ex… plusieurs fois ?",
    "Qui est le plus susceptible d’avoir le plus de fantasmes jamais avoués ?",
    "Qui est le plus susceptible de demander l’avis du groupe avant de répondre à son crush ?",
    "Qui est le plus susceptible d’avoir déjà eu un plan dans une voiture ?",
    "Qui est le plus susceptible d’avoir un fantasme sur une célébrité… et d’en parler sans gêne ?",
    "Qui est le plus susceptible d’avoir déjà fait un appel vidéo très, très privé ?",
    "Qui est le plus susceptible d’avoir déjà dragué quelqu’un en utilisant une réplique de film ?",
    "Qui est le plus susceptible de finir la soirée à embrasser quelqu’un ici ?",
    "Qui est le plus susceptible d’avoir des préférences très précises au lit… et de les annoncer d’entrée ?",
    "Qui est le plus susceptible d’avoir eu un coup de cœur pour le témoin à un mariage ?",
    "Qui est le plus susceptible d’avoir déjà regretté un tatouage fait pour un ex ?",
  ]
};

// Questions ajoutées (modes Party et Chaos, qui en avaient moins).
export const MORE_QUESTIONS = {
  Party: [
    "Qui est le plus susceptible de s'endormir en pleine soirée ?",
    "Qui est le plus susceptible de perdre son téléphone ce soir ?",
    "Qui est le plus susceptible de lancer un karaoké sans prévenir ?",
    "Qui est le plus susceptible de finir la soirée en pyjama chez quelqu'un d'autre ?",
    "Qui est le plus susceptible de commander un kebab à 4 h du matin ?",
    "Qui est le plus susceptible de raconter la même anecdote trois fois ?",
    "Qui est le plus susceptible de se faire refouler d'une boîte ?",
    "Qui est le plus susceptible de danser sur une table ?",
    "Qui est le plus susceptible d'envoyer un message vocal de 5 minutes ?",
    "Qui est le plus susceptible de partir sans dire au revoir ?",
    "Qui est le plus susceptible de devenir célèbre sur TikTok ?",
    "Qui est le plus susceptible d'oublier l'anniversaire de son meilleur ami ?",
    "Qui est le plus susceptible de rater son train ou son avion ?",
    "Qui est le plus susceptible de tomber amoureux en vacances ?",
    "Qui est le plus susceptible de dire « c'est la dernière » et de reprendre un verre ?",
    "Qui est le plus susceptible de se perdre dans sa propre ville ?",
    "Qui est le plus susceptible de faire un discours émouvant bourré ?",
    "Qui est le plus susceptible de mettre trois heures à se préparer ?",
    "Qui est le plus susceptible de devenir influenceur ?",
    "Qui est le plus susceptible de gagner à un jeu télé ?",
    "Qui est le plus susceptible de rire à un enterrement ?",
    "Qui est le plus susceptible de se lancer dans un business improbable ?",
    "Qui est le plus susceptible d'appeler son ex ce soir ?",
    "Qui est le plus susceptible de mentir sur son âge ?",
    "Qui est le plus susceptible de survivre à une apocalypse zombie ?",
    "Qui est le plus susceptible de mourir en premier dans un film d'horreur ?",
    "Qui est le plus susceptible de partir vivre à l'autre bout du monde ?",
    "Qui est le plus susceptible de tout dépenser le jour de la paie ?",
    "Qui est le plus susceptible de stalker quelqu'un sur Instagram jusqu'en 2015 ?",
    "Qui est le plus susceptible de se battre avec un distributeur de boissons ?"
  ],
  Chaos: [
    "Qui est le plus susceptible de finir la soirée dans un endroit improbable ?",
    "Qui est le plus susceptible d'embrasser quelqu'un de la room ce soir ?",
    "Qui est le plus susceptible d'avoir un dossier compromettant sur tout le monde ?",
    "Qui est le plus susceptible de mentir pendant ce jeu ?",
    "Qui est le plus susceptible de se réveiller sans savoir où il est ?",
    "Qui est le plus susceptible de créer un drama de groupe ?",
    "Qui est le plus susceptible de faire un truc complètement débile pour un pari ?",
    "Qui est le plus susceptible d'avoir déjà menti à tout le monde ici ?",
    "Qui est le plus susceptible de se faire larguer par message ?",
    "Qui est le plus susceptible de larguer quelqu'un par message ?",
    "Qui est le plus susceptible de vomir avant minuit ?",
    "Qui est le plus susceptible de faire un tatouage regrettable ?",
    "Qui est le plus susceptible de s'incruster à un mariage ?",
    "Qui est le plus susceptible d'avoir un compte secret sur les réseaux ?",
    "Qui est le plus susceptible de se faire virer pour une connerie ?",
    "Qui est le plus susceptible de trahir un secret après deux verres ?",
    "Qui est le plus susceptible de flirter avec le serveur ou la serveuse ?",
    "Qui est le plus susceptible de dormir dans la baignoire ?",
    "Qui est le plus susceptible de parier toute sa paie au casino ?",
    "Qui est le plus susceptible de faire une déclaration d'amour bourré ?",
    "Qui est le plus susceptible de se battre pour la dernière part de pizza ?",
    "Qui est le plus susceptible d'avoir déjà été recalé d'un date ?",
    "Qui est le plus susceptible de garder une capture d'écran de chaque conversation ?",
    "Qui est le plus susceptible de mettre le feu à une cuisine ?",
    "Qui est le plus susceptible de partir en Vegas sur un coup de tête ?",
    "Qui est le plus susceptible d'avoir un plan B pour chaque soirée ?",
    "Qui est le plus susceptible d'être le traître dans Mission Traître ?",
    "Qui est le plus susceptible d'avoir triché à un examen ?",
    "Qui est le plus susceptible de se marier sur un coup de tête ?",
    "Qui est le plus susceptible de finir dans un reportage « Enquête exclusive » ?"
  ]
};
