// Contenu de la Bombe : catégories, questions/défis (par mode de soirée), punitions,
// modificateurs de manche. Repris de l'ancienne version, catégories enrichies.

export const CATEGORIES = [
  "Pays", "Marques", "Animaux", "Films", "Séries", "Prénoms", "Footballeurs",
  "Pokémon", "Alcools", "Villes", "Chansons", "Métiers", "Objets de cuisine",
  "Desserts", "Sports", "Jeux vidéo", "Mots en anglais", "Célébrités", "Applications", "Excuses nulles"
];

// Catégories ajoutées
export const MORE_CATEGORIES = [
  "Marques de voiture",
  "Pays d'Europe",
  "Capitales",
  "Fruits",
  "Légumes",
  "Fromages",
  "Plats français",
  "Cocktails",
  "Marques de bière",
  "Super-héros",
  "Méchants de films",
  "Dessins animés",
  "Disney",
  "Personnages de Harry Potter",
  "Rappeurs français",
  "Chanteurs",
  "Groupes de musique",
  "Instruments",
  "Danses",
  "Clubs de foot",
  "Joueurs de NBA",
  "Sports olympiques",
  "Marques de vêtements",
  "Marques de téléphone",
  "Réseaux sociaux",
  "Youtubeurs",
  "Émissions de télé",
  "Couleurs",
  "Parties du corps",
  "Métiers dangereux",
  "Choses dans une salle de bain",
  "Choses qu'on trouve à la plage",
  "Choses dans un frigo",
  "Mots qui riment avec « bière »",
  "Insultes gentilles",
  "Excuses pour ne pas venir en soirée",
  "Choses qu'on fait à 3 h du matin",
  "Fast-foods",
  "Bonbons",
  "Céréales",
  "Marques de chips",
  "Jeux de société",
  "Pokémon de la 1re génération",
  "Personnages de jeux vidéo",
  "Consoles",
  "Voitures de films",
  "Héros de mangas",
  "Mots en anglais utilisés en français",
  "Villes de France",
  "Départements",
  "Fleuves et rivières",
  "Îles",
  "Monuments",
  "Oiseaux",
  "Animaux marins",
  "Insectes",
  "Races de chiens",
  "Prénoms de filles",
  "Prénoms de garçons",
  "Noms d'animaux de compagnie",
  "Objets dans un sac à main",
  "Choses rondes",
  "Choses jaunes",
  "Choses qui piquent",
  "Mots de 3 lettres",
  "Mots qui commencent par « super »",
  "Langues",
  "Matières à l'école",
  "Personnages historiques",
  "Inventions",
  "Planètes et étoiles",
  "Films d'horreur",
  "Comédies françaises",
  "Séries Netflix",
  "Applis de rencontre",
  "Choses qu'on dit en soirée",
  "Raisons de se disputer",
  "Phobies",
  "Sorts ou formules magiques",
  "Signes du zodiaque"
];

export const QUESTIONS = {
  Chill: [
    "Cite 3 boissons sans alcool.",
    "Cite 3 snacks de soirée.",
    "Cite 3 excuses pour arriver en retard.",
    "Cite 3 chansons connues.",
    "Cite 3 films cultes.",
    "Cite 3 applis sur ton téléphone.",
    "Cite 3 objets sur la table.",
    "Cite 3 mots qui font rire.",
    "Cite 3 prénoms du groupe.",
    "Cite 3 choses qu’on perd souvent.",
    "Cite 3 desserts.",
    "Cite 3 marques de soda.",
    "Cite 3 plats rapides.",
    "Cite 3 animaux mignons.",
    "Cite 3 villes françaises.",
    "Cite 3 pays d’Europe.",
    "Cite 3 sports faciles à citer.",
    "Cite 3 couleurs.",
    "Cite 3 émoticônes.",
    "Cite 3 super-héros.",
    "Cite 3 dessins animés.",
    "Cite 3 objets dans une cuisine.",
    "Cite 3 trucs qu’on met dans un sac.",
    "Cite 3 raisons de faire une pause.",
    "Cite 3 jeux de société.",
    "Cite 3 choses qui coûtent moins de 5 euros.",
    "Cite 3 objets rouges.",
    "Cite 3 choses froides.",
    "Cite 3 choses chaudes.",
    "Cite 3 mots anglais connus.",
    "Cite 3 fruits.",
    "Cite 3 légumes.",
    "Cite 3 fromages.",
    "Cite 3 marques de voiture.",
    "Cite 3 capitales.",
    "Cite 3 instruments de musique.",
    "Cite 3 métiers.",
    "Cite 3 Pokémon.",
    "Cite 3 personnages Disney.",
    "Cite 3 chanteurs français.",
    "Cite 3 séries Netflix.",
    "Cite 3 jeux vidéo.",
    "Cite 3 mots qui riment avec « soirée ».",
    "Cite 3 mots qui commencent par « Z ».",
    "Cite 3 choses qu’on trouve dans une salle de bain.",
    "Cite 3 choses qui volent.",
    "Cite 3 choses rondes.",
    "Cite 3 choses qui piquent.",
    "Cite 3 parfums de glace.",
    "Cite 3 garnitures de pizza.",
    "Cite 3 sports d’hiver.",
    "Cite 3 sports de raquette.",
    "Cite 3 animaux de la ferme.",
    "Cite 3 animaux de la savane.",
    "Cite 3 animaux marins.",
    "Cite 3 insectes.",
    "Cite 3 oiseaux.",
    "Cite 3 arbres.",
    "Cite 3 fleurs.",
    "Cite 3 planètes.",
    "Cite 3 jours fériés.",
    "Cite 3 mois de l’année avec un « r ».",
    "Cite 3 langues étrangères.",
    "Cite 3 monuments célèbres.",
    "Cite 3 marques de vêtements.",
    "Cite 3 réseaux sociaux.",
    "Cite 3 youtubeurs ou streamers.",
    "Cite 3 footballeurs.",
    "Cite 3 héros de mangas.",
    "Cite 3 princesses Disney.",
    "Cite 3 personnages de Harry Potter.",
    "Cite 3 choses qu’on emmène à la plage.",
    "Cite 3 choses qu’on fait le dimanche.",
    "Cite 3 pièces d’une maison.",
    "Cite 3 moyens de transport.",
    "Cite 3 choses qui font du bruit.",
    "Cite 3 choses jaunes.",
    "Cite 3 choses vertes.",
    "Cite 3 choses qu’on met au frigo.",
    "Cite 3 desserts au chocolat.",
    "Cite 3 plats italiens.",
    "Cite 3 plats asiatiques.",
    "Cite 3 viennoiseries.",
    "Cite 3 bonbons.",
    "Cite 3 céréales du petit-déjeuner.",
    "Cite 3 dessins animés des années 90.",
    "Cite 3 chansons de Disney.",
    "Cite 3 jeux de cour de récré.",
    "Fais le bruit d’un animal, le suivant devine.",
    "Imite un personnage célèbre en 3 mots.",
    "Finis la phrase : « Je ne pourrais jamais vivre sans… »",
    "Dis un mot de plus de 10 lettres.",
    "Cite 3 choses qu’on fait en vacances.",
    "Cite 3 métiers qui commencent par « P ».",
    "Cite 3 objets en bois.",
    "Cite 3 objets en métal.",
    "Cite 3 marques de téléphone.",
    "Cite 3 saveurs de chips.",
    "Cite 3 couleurs qui ne sont pas dans l’arc-en-ciel.",
    "Cite 3 films d’animation.",
    "Cite 3 choses qu’on trouve dans une trousse.",
    "Cite 3 chiens célèbres.",
  ],
  Party: [
    "Cite 3 alcools.",
    "Cite 3 cocktails.",
    "Cite 3 raisons de boire.",
    "Cite 3 chansons de soirée.",
    "Cite 3 choses qu’on crie bourré.",
    "Cite 3 jeux d’alcool.",
    "Cite 3 marques de bière.",
    "Cite 3 endroits où sortir.",
    "Cite 3 trucs qu’on regrette le lendemain.",
    "Cite 3 excuses pour reprendre un verre.",
    "Cite 3 phrases de soirée.",
    "Cite 3 danses ridicules.",
    "Cite 3 objets qu’on perd en soirée.",
    "Cite 3 boissons à mélanger.",
    "Cite 3 sons qui mettent l’ambiance.",
    "Cite 3 raisons de faire un after.",
    "Cite 3 règles de jeu d’alcool.",
    "Cite 3 mots interdits en soirée.",
    "Cite 3 choses à dire avant un shot.",
    "Cite 3 signes que quelqu’un est bourré.",
    "Cite 3 snacks d’après-soirée.",
    "Cite 3 verres différents.",
    "Cite 3 défis faciles.",
    "Cite 3 prétextes pour trinquer.",
    "Cite 3 lieux improbables pour finir la soirée.",
    "Cite 3 choses à éviter en boîte.",
    "Cite 3 phrases de DJ nul.",
    "Cite 3 objets utiles en soirée.",
    "Cite 3 façons de porter un toast.",
    "Cite 3 raisons d’avoir soif.",
    "Cite 3 chansons à hurler en karaoké.",
    "Cite 3 tubes de l’été.",
    "Cite 3 marques de vodka ou de rhum.",
    "Cite 3 shots célèbres.",
    "Cite 3 boîtes de nuit ou bars connus.",
    "Cite 3 festivals de musique.",
    "Cite 3 DJ célèbres.",
    "Cite 3 rappeurs français.",
    "Cite 3 chansons des années 2000.",
    "Cite 3 danses de soirée.",
    "Cite 3 pas de danse célèbres.",
    "Cite 3 choses qu’on commande au bar.",
    "Cite 3 jeux de cartes à boire.",
    "Cite 3 accessoires de déguisement.",
    "Cite 3 thèmes de soirée déguisée.",
    "Cite 3 choses qu’on met dans un cocktail.",
    "Cite 3 fruits qu’on met dans un cocktail.",
    "Cite 3 trucs qu’on mange à 4h du matin.",
    "Cite 3 phrases de drague nulles.",
    "Cite 3 applis de rencontre.",
    "Cite 3 endroits pour un premier date.",
    "Cite 3 films de soirée pyjama.",
    "Cite 3 chansons de mariage.",
    "Cite 3 choses qu’on oublie en partant de soirée.",
    "Cite 3 trucs qu’on dit au videur.",
    "Cite 3 types de verres.",
    "Cite 3 vins ou régions de vin.",
    "Cite 3 marques de champagne.",
    "Cite 3 bières étrangères.",
    "Cite 3 sirops.",
    "Cite 3 chansons de Beyoncé ou de Rihanna.",
    "Cite 3 chansons de Johnny ou de Céline Dion.",
    "Cite 3 chanteurs morts trop tôt.",
    "Cite 3 groupes de rock.",
    "Cite 3 chansons qui font danser les parents.",
    "Cite 3 chansons pour un slow.",
    "Cite 3 trucs qu’on poste en story en soirée.",
    "Cite 3 choses qu’on crie sur la piste.",
    "Cite 3 façons de dire « santé » dans une autre langue.",
    "Cite 3 trucs qu’on trouve dans un sac de soirée.",
    "Cite 3 sauces de kebab.",
    "Cite 3 fast-foods.",
    "Cite 3 émissions de télé-réalité.",
    "Cite 3 candidats de télé-réalité.",
    "Cite 3 couples de stars.",
    "Cite 3 chansons d’Aya Nakamura ou de Jul.",
    "Cite 3 boissons énergisantes ou softs de soirée.",
    "Cite 3 jeux de soirée.",
    "Finis la phrase : « Ce soir, je vais… »",
    "Imite un DJ qui chauffe la salle.",
    "Fais un pas de danse, le suivant doit l’imiter.",
    "Chante 3 mots d’un tube, le suivant devine.",
    "Porte un toast en 5 mots.",
    "Dis le prénom de quelqu’un ici et un compliment.",
    "Cite 3 choses qu’on fait dans un after.",
    "Cite 3 trucs qu’on dit en arrivant en retard à une soirée.",
    "Cite 3 excuses pour partir tôt.",
    "Cite 3 signes qu’une soirée est réussie.",
    "Cite 3 choses qu’on boit le lendemain.",
    "Cite 3 remèdes anti-gueule de bois.",
    "Cite 3 chansons avec un prénom dans le titre.",
    "Cite 3 chansons avec « amour » dans le titre.",
    "Cite 3 films avec une scène de fête.",
    "Cite 3 jeux à faire en voiture.",
    "Cite 3 villes de fête en Europe.",
    "Cite 3 îles de vacances.",
    "Cite 3 choses qu’on ramène de vacances.",
    "Cite 3 sports qu’on fait en club… ou pas.",
    "Cite 3 trucs à faire pour un enterrement de vie de garçon ou de jeune fille.",
    "Cite 3 accessoires de photobooth.",
  ],
  Chaos: [
    "Cite 3 personnes à qui il ne faut pas envoyer de message bourré.",
    "Cite 3 messages dangereux à envoyer à son ex.",
    "Cite 3 raisons de supprimer une story.",
    "Cite 3 situations gênantes en soirée.",
    "Cite 3 mensonges pour cacher son état.",
    "Cite 3 phrases dites par quelqu’un qui est trop bourré.",
    "Cite 3 décisions nulles après minuit.",
    "Cite 3 red flags en soirée.",
    "Cite 3 choses qu’il ne faut jamais filmer.",
    "Cite 3 moyens de créer un drama.",
    "Cite 3 excuses après une dinguerie.",
    "Cite 3 phrases impossibles à assumer.",
    "Cite 3 trucs qu’on nie le lendemain.",
    "Cite 3 signes d’un mauvais plan.",
    "Cite 3 façons de se faire griller.",
    "Cite 3 raisons de paniquer pour rien.",
    "Cite 3 mauvaises idées de groupe.",
    "Cite 3 choses à ne pas poster.",
    "Cite 3 situations où il faut appeler un pote.",
    "Cite 3 phrases à ne pas dire à son crush.",
    "Cite 3 objets qu’on peut casser en soirée.",
    "Cite 3 moyens de perdre sa dignité.",
    "Cite 3 confessions trop honnêtes.",
    "Cite 3 choses à ne pas envoyer en vocal.",
    "Cite 3 raisons d’être dans le débrief.",
    "Cite 3 moments où il faut rentrer.",
    "Cite 3 prétextes pour disparaître.",
    "Cite 3 choses que le groupe ne pardonne pas.",
    "Cite 3 mauvaises excuses de lendemain.",
    "Cite 3 situations de honte.",
    "Cite 3 excuses pour ne pas répondre à un message.",
    "Cite 3 choses à ne jamais dire à un premier date.",
    "Cite 3 sujets à éviter à un repas de famille.",
    "Cite 3 phrases qui annoncent une rupture.",
    "Cite 3 trucs qu’on cache à ses parents.",
    "Cite 3 mensonges qu’on dit au travail.",
    "Cite 3 choses qu’on fait quand on est seul chez soi.",
    "Cite 3 raisons de bloquer quelqu’un.",
    "Cite 3 choses qui énervent en colocation.",
    "Cite 3 phrases de mauvaise foi.",
    "Cite 3 façons de se faire griller en mentant.",
    "Cite 3 trucs qu’on dit pour finir une conversation.",
    "Cite 3 choses qu’on google en cachette.",
    "Cite 3 défauts qu’on cache au début d’une relation.",
    "Cite 3 phrases typiques d’un ex.",
    "Cite 3 signes qu’un date se passe mal.",
    "Cite 3 trucs à ne pas faire à un mariage.",
    "Cite 3 pires cadeaux à offrir.",
    "Cite 3 choses qu’on dit quand on a fait une bêtise.",
    "Cite 3 façons de dire « non » sans dire non.",
    "Cite 3 situations où on fait semblant de rire.",
    "Cite 3 excuses pour annuler au dernier moment.",
    "Cite 3 trucs gênants dans un ascenseur.",
    "Cite 3 phrases qu’on n’ose pas dire à son boss.",
    "Cite 3 trucs qu’on vole à l’hôtel.",
    "Cite 3 pires endroits pour s’endormir.",
    "Cite 3 choses qu’on fait en réunion au lieu d’écouter.",
    "Cite 3 trucs qu’on dit quand on a oublié un prénom.",
    "Cite 3 choses qui font paniquer en ouvrant ses messages le lendemain.",
    "Cite 3 façons de quitter une soirée discrètement.",
    "Cite 3 excuses de retard improbables.",
    "Cite 3 phrases de parents énervés.",
    "Cite 3 pires noms pour un enfant.",
    "Cite 3 métiers qu’on ne ferait jamais.",
    "Cite 3 pires jobs d’été.",
    "Cite 3 phrases de prof pénible.",
    "Cite 3 trucs qu’on fait en cachette au bureau.",
    "Cite 3 choses qu’on regrette d’avoir acheté.",
    "Cite 3 situations où on prétend être occupé.",
    "Cite 3 choses à ne pas dire à un enterrement.",
    "Cite 3 sujets qui déclenchent un débat.",
    "Cite 3 choses qu’on dit à quelqu’un qu’on veut quitter.",
    "Cite 3 raisons de ghoster.",
    "Cite 3 signes qu’un pote ment.",
    "Cite 3 trucs qu’on fait pour avoir l’air occupé au téléphone.",
    "Cite 3 pires moments pour péter.",
    "Cite 3 phrases qu’on dit en voyant un ex.",
    "Cite 3 excuses pour ne pas prêter de l’argent.",
    "Finis la phrase : « La pire chose que j’ai faite ce mois-ci, c’est… »",
    "Désigne la personne ici la plus susceptible de mentir, et passe.",
    "Dis un secret… sur toi, en 5 mots.",
    "Imite quelqu’un ici en une phrase, le suivant devine.",
    "Cite 3 pires surnoms.",
    "Cite 3 choses qu’on garde de son ex.",
    "Cite 3 trucs qui rendent jaloux.",
    "Cite 3 phrases à dire pour calmer un drama.",
    "Cite 3 excuses pour échapper à une amende de stationnement.",
    "Cite 3 trucs qu’on fait en retard le matin.",
    "Cite 3 raisons de ne pas venir à une soirée.",
    "Cite 3 trucs qu’on fait juste pour la photo.",
    "Cite 3 choses insupportables chez un voisin.",
    "Cite 3 phrases à ne pas envoyer à 3h du matin.",
    "Cite 3 pires idées de tatouage.",
    "Cite 3 trucs bizarres dans un frigo de colocation.",
    "Cite 3 choses qu’on fait quand le Wi-Fi coupe.",
    "Cite 3 pires bruits la nuit.",
    "Cite 3 trucs qu’on dit pour avoir le dernier mot.",
    "Cite 3 pires questions de belle-famille.",
  ],
  Hardcore: [
    "Cite 3 excuses nulles après une soirée.",
    "Cite 3 décisions de fin de soirée horribles.",
    "Cite 3 choses qu’on nie toujours le lendemain.",
    "Cite 3 signes que la soirée part trop loin.",
    "Cite 3 façons de se faire roast.",
    "Cite 3 défis qui tournent mal.",
    "Cite 3 raisons de prendre un shot.",
    "Cite 3 façons de ruiner son lendemain.",
    "Cite 3 preuves qu’il faut arrêter.",
    "Cite 3 endroits insolites pour un premier baiser.",
    "Cite 3 choses qui rendent quelqu’un attirant.",
    "Cite 3 phrases de drague qui marchent (vraiment).",
    "Cite 3 pires phrases au lit.",
    "Cite 3 parties du corps qu’on regarde en premier.",
    "Cite 3 films avec une scène torride.",
    "Cite 3 chansons sexy.",
    "Cite 3 trucs qu’on fait avant un date.",
    "Cite 3 sous-vêtements.",
    "Cite 3 endroits où on ne devrait pas s’embrasser.",
    "Cite 3 fantasmes classiques.",
    "Cite 3 trucs gênants pendant un premier baiser.",
    "Cite 3 choses qu’on dit en ramenant quelqu’un chez soi.",
    "Cite 3 excuses pour ne pas rester dormir.",
    "Cite 3 raisons de retourner avec son ex.",
    "Cite 3 signes que quelqu’un te drague.",
    "Cite 3 stars que tu trouves canon.",
    "Cite 3 trucs qu’on fait le lendemain d’un coup d’un soir.",
    "Cite 3 mots doux ridicules.",
    "Cite 3 positions de yoga… ou autres.",
    "Cite 3 choses qu’on cache dans sa table de nuit.",
    "Cite 3 trucs qu’on envoie à 2h du matin.",
    "Cite 3 phrases qu’on dit quand on se fait surprendre.",
    "Cite 3 endroits où on a envie de faire l’amour.",
    "Cite 3 qualités d’un bon coup.",
    "Cite 3 red flags au lit.",
    "Cite 3 choses qu’on ment sur une appli de rencontre.",
    "Cite 3 trucs qui tuent le désir.",
    "Cite 3 pires excuses après avoir trompé (pour de rire).",
    "Cite 3 choses à dire à un ex qui revient.",
    "Cite 3 trucs qu’on fait pour rendre quelqu’un jaloux.",
    "Cite 3 accessoires coquins.",
    "Cite 3 couples de séries qui ont trop de chimie.",
    "Cite 3 chansons pour une nuit romantique.",
    "Cite 3 parfums qui séduisent.",
    "Cite 3 tenues irrésistibles.",
    "Désigne la personne ici la plus séduisante, et passe vite.",
    "Désigne qui ici a le plus gros body count selon toi, et passe.",
    "Finis la phrase : « Mon fantasme, c’est… » (version soft)",
    "Fais un clin d’œil séducteur au joueur suivant.",
    "Dis le prénom de ton premier baiser.",
    "Dis le prénom de ton premier crush.",
    "Murmure un mot doux au joueur suivant.",
    "Cite 3 trucs qu’on fait sous la douche… à deux.",
    "Cite 3 choses qu’on regrette après une nuit.",
    "Cite 3 façons de dire « on rentre ensemble ? ».",
    "Cite 3 trucs qu’on dit à quelqu’un qu’on trouve canon.",
    "Cite 3 trucs qu’on cherche chez un plan cul.",
    "Cite 3 situations où on s’est fait griller par un coloc.",
    "Cite 3 pires endroits pour un date.",
    "Cite 3 trucs qu’on fait pour séduire en boîte.",
    "Cite 3 phrases à ne jamais dire après un baiser.",
    "Cite 3 bruits gênants la nuit.",
    "Cite 3 choses qu’on ne prête jamais à son ex.",
    "Cite 3 couples célèbres qui ont rompu.",
    "Cite 3 films romantiques à regarder à deux.",
    "Cite 3 trucs qu’on fait pour oublier un ex.",
    "Cite 3 excuses pour stalker son ex.",
    "Cite 3 indices qu’un pote a passé la nuit avec quelqu’un.",
    "Cite 3 choses qu’on dit au walk of shame.",
    "Cite 3 trucs qu’on fait quand on a trop bu.",
    "Cite 3 endroits où on s’est déjà endormi bourré.",
    "Cite 3 pires mélanges d’alcool.",
    "Cite 3 signes qu’il faut rentrer.",
    "Cite 3 trucs qu’on dit au réveil après une grosse soirée.",
    "Cite 3 choses qu’on retrouve dans sa poche le lendemain.",
    "Cite 3 messages qu’on envoie bourré.",
    "Cite 3 personnes qu’on appelle bourré.",
    "Cite 3 excuses pour la gueule de bois au boulot.",
    "Cite 3 choses qu’on promet de ne plus jamais faire.",
    "Cite 3 trucs qu’on fait en rentrant à 6h.",
    "Cite 3 choses qu’on mange en rentrant de soirée.",
    "Cite 3 pires endroits pour vomir.",
    "Cite 3 trucs qu’on dit pour avoir un dernier verre.",
    "Cite 3 manières de se faire virer d’une soirée.",
    "Cite 3 choses qu’on avoue seulement bourré.",
    "Cite 3 pires idées après 3h du matin.",
    "Cite 3 trucs qui finissent en story honteuse.",
    "Cite 3 choses qu’on cache à son ou sa partenaire.",
    "Cite 3 pires excuses pour ne pas répondre à son crush.",
    "Cite 3 trucs qu’on fait pour impressionner un crush.",
    "Cite 3 surnoms coquins.",
    "Cite 3 trucs qu’on regrette d’avoir dit à son ex.",
    "Cite 3 tenues de soirée trop osées.",
    "Cite 3 chansons pour un strip-tease.",
    "Cite 3 trucs qu’on fait à 2 dans un ascenseur.",
    "Désigne qui ici embrasserait le premier ce soir, et passe.",
    "Désigne qui ici a le pire goût en ex, et passe.",
    "Finis la phrase : « Le pire date de ma vie, c’est quand… »",
    "Finis la phrase : « Je n’avouerai jamais que… »",
    "Dis le pire endroit où tu as dragué quelqu’un.",
  ],
};

async function initGame() {
  const roomSnap = await getDoc(roomRef);

  if (roomSnap.exists()) {
    const roomData = roomSnap.data();
    players = roomData.players || players;
    bombGameMode = roomData.bombGameMode || roomData.gameState?.bombGameMode || bombGameMode;
    localStorage.setItem("partyhubBombMode", bombGameMode);
  }

  roomBadge.textContent = `Room ${roomCode}`;
  modeText.textContent = `${selectedPartyMode} · ${bombGameMode === "syllables" ? "Syllabes" : "Libre"}`;
  drinkLevelText.textContent = getDrinkLevelLabel();
  playersText.textContent = players.length;
  roundText.textContent = currentRound;

  if (players.length < 2) {
    questionText.textContent = "Ajoute au moins 2 joueurs pour jouer.";
    passBombBtn.disabled = true;
    nextBombBtn.classList.add("hidden");
    return;
  }

  passBombBtn.disabled = true;
  passBombBtn.textContent = "Attente du joueur concerné";

  listenToBombState();

  if (isHost) {
    createRoundState(1, 0);
  } else {
    setTimeout(async () => {
      if (!firstBombStateChecked) {
        const fresh = await getDoc(roomRef);
        if (fresh.exists() && !fresh.data().bombTimerState) {
          await createRoundState(1, 0, true);
        }
      }
    }, 900);
  }
}

export const MODIFIERS = [
  { id: "none", label: "Aucun", instruction: "Réponds puis passe la bombe avant l’explosion." },
  { id: "two_seconds", label: "Réponse éclair ⚡", instruction: "Tu dois répondre très vite avant de passer." },
  { id: "no_hesitation", label: "Zéro hésitation 🚫", instruction: "Pas de blanc, pas de 'euh', sinon le groupe peut te refuser." },
  { id: "letter", label: "Lettre imposée 🔠", instruction: "Ta réponse doit commencer par la lettre affichée." },
  { id: "double_pass", label: "Double passe 🌀", instruction: "Quand tu passes, la bombe saute un joueur." },
  { id: "voice", label: "Voix ridicule 🎭", instruction: "Réponds avec une voix ridicule avant de passer." }
];
